### PR TITLE
Add Generic STM32F103Rx boards

### LINKED ISSUE #556: STM32F103RET6
**Board description:**
 - Name: STM32F103RET6 "Blue button" Development board
 - Link to all relevant information:
   * Documentations: https://github.com/mcauser/BLUE_BUTTON_F103RET6/
   * Where this hardware can be purchased: https://www.aliexpress.com/item/32787019266.html

"STM32F103xE" define can be found in some places in the Arduino_Core_STM32 but currently there are no board definitions for it.

### PR DESCRIPTION
**Pull request by fpistm**
Four variants available:
 * STM32F103R8T6
 * STM32F103RBT6
 * STM32F103RCT6
 * STM32F103RET6

Based on @pkourany work.

If someone can test them this would be fine as I do not have those boards.
Thanks in advance.

Fixes #556

### CODE REVIEW

**Comment by hamed-ta** [comment]
Hi, I can't find the board ID for using STM32F103RCT6 custom board in PIO which loaded Arduino_Core_STM32,

**Comment by fpistm** [comment]
Well, I can't help on this, I never used PIO and as said in your previous issue here only Arduino IDE is supported.

**Comment by hamed-ta** [comment]
well, the Arduino IDE doesn't have the basic facilities of an IDE and it's really difficult to work with, so please think of a better IDE such as PIO support.

**Comment by fpistm** [comment]
> 
> 
> well, the Arduino IDE doesn't have the basic facilities of an IDE and it's really difficult to work with, so please think of a better IDE such as PIO support.

Goal of this core is to provide STM32 support in Arduino.
I know Arduino IDE is limited anyway this is the reference IDE. PIO provides support to integrates it so you have to ask there: 
https://github.com/platformio/platform-ststm32

**Comment by pfeerick** [comment]
FYI, to change to the STM32duino on PlatformIO for a board that defaults to using the 'maple' core, just add `board_build.core = stm32` to the project `platformio.ini` configuration file to override that default value.

**Comment by hamed-ta** [comment]
it seems that that the new variables will be included in the next release (Arduino Core for STM32 v1.9.0) right ?

**Comment by fpistm** [comment]
yes, anyway, I think you can use the git repo. It should be documented in PIO.
@valeros ?

**Comment by hamed-ta** [comment]
but I can see that the variants (Generic STM32F103R(8/B/C/E)) are add in Arduino Core for STM32 1.7.0 release ?!!

**Comment by fpistm** [comment]
yes those version but the other will be added to the 1.9.0

**Comment by fpistm** [comment]
Ah, you want use the RC so yes it is already available since 1.7.0. So if it's not work with PIO then ask on PIO support.

**Comment by hamed-ta** [comment]
Yea, good, I'm asking them... I think they just need to add the right board configuration file to the PIO boards.

**Pull request merged**
