### PR TITLE
Disable USART IRQ in uart_write and uart_debug_write

### PR DESCRIPTION
**Pull request by benwaffle**
This PR fixes issues #494 and #467 for printf();

I want to be able to use printf() with Serial.write() and Serial.read(). See discussion in both issues mentioned above.

**Validation**

See the example code in #494

---

I'm not sure how to:

- Get IRQn_Type values from a UART_TypeDef
- Determine which UARTs are defined for a given device 
- Whether I need to set the priority when enabling the interrupt

### CODE REVIEW

**Comment by fpistm** [comment]
Hi @benwaffle 
Thanks for the PR.
Could you squash some commits to clean the PR?

Those can be merged in one:

> Disable uart interrupt in uart_debug_write
> redundant
> remove broken/unneeded code

And those one:

> Fix UART error callback (clear flags and restart receive IT)
> fix astyle


Then the PR should contains only 3 commits:

> Disable uart interrupt in uart_debug_write
> Fix serial port full-duplex bug
> Fix UART error callback (clear flags and restart receive IT)

Thanks in advance

**Comment by benwaffle** [comment]
@fpistm squashed

**Comment by fpistm** [comment]
Thanks a lot @benwaffle. I will rview and test it as soon as possible.

**Comment by fpistm** [comment]
@benwaffle 
using your code example, I only receive and print one time?
Is this really fix your issue ?

**Comment by fpistm** [comment]
@benwaffle 
using your code example, I only receive and print one time?
Is this really fix your issue ?

**Comment by benwaffle** [comment]
yes, it worked for me. make sure that you have the `Disable uart interrupt in uart_debug_write` patch applied

**Comment by fpistm** [comment]
I got it but it is not functional on my side.

**Comment by benwaffle** [comment]
I can test it again today.

**Comment by fpistm** [comment]
Ok, in fact it fails with Arduino Serial monitor.
Using Putty terminal, it works.
Anyway, I need deeper review/tests.

**Comment by fpistm** [comment]
@benwaffle, @ppescher ,
I've made some test and dig into the code.
The result is the #502 .
Please could you review and test it?

**Comment by fpistm** [comment]
This one is superseded by #502

**Pull request closed without merging**
