### PR TITLE
fix: Cygnet USER_BTN mapping

### PR DESCRIPTION
**Pull request by zfields**
We made hardware modifications to the Cygnet dev kit to support deep sleep. The following changes reflect those updates.

### CODE REVIEW

**Review by fpistm — APPROVED** [review]

**Comment by zfields** [comment]
@fpistm I noticed when I was testing that I was limited to approximately 10 interrupts running simultaneously. Would this be expected behavior, or do I need to further improve my board definition?

**Comment by fpistm** [comment]
Hi @zfields 
I don't have access to your sketch

**Comment by fpistm** [comment]
Hi @zfields 
First, next time, please open a discussion. Comments on PR merged is not easy to follow mainly when it is not link to the PR subject.
For me there is no issue, only a missing knowledge on the STM32 EXTI.
You can't have 1 interrupt for each pin. EXTI does not take care of GPIO port only GPIO pin number.
So you can have 16 EXTI, one per GPIO pin number from 0 to 15.
If you configure interrupt on PA0 then the handler it is the same for PB0, PC0,....
In your case for the Cygnet the latest handler attached will be the one called for all pin with the same pin number:
| Arduino pin number | STM32 alias | GPIO pin number | comment |
| --- | --- | --- | --- |
| A0  | PA0 | 0 |  ISR_d11 not ISR_a0  |
| A1  | PA1 | 1 | ISR_a4 not ISR_a1  | 
| A2  | PA2 | 2 | ISR_a2 | 
| A3  | PA3 | 3 | ISR_a3 |
| A4  | PB1 | 1 | ISR_a4 | 
| A5  | PA7 | 7 | ISR_a5 | 
| D5  | PB8 | 8 | ISR_d5 | 
| D6  | PB9 | 9 | ISR_d6 | 
| D9  | PB14 | 14 | ISR_d9 | 
| D10 | PB13 | 13 | ISR_user_btn not ISR_d10 |  
| D11 | PB0 | 0 | ISR_d11 | 
| D12 | PB15 | 15 | ISR_d12 | 
| D13 | PB4 | 4 | ISR_d13 |   
| USER_BTN | PC13 |  13 |  ISR_user_btn |  

So as you can see you expect 14 isr handler but only 11 are called.

**Comment by zfields** [comment]
@fpistm Thank you for your thorough answer. I love your chips and I love learning deeper about them.

I really do appreciate your time.

Next time I will open a discussion. :+1:

**Pull request merged**
