### PR TITLE
Add support RAK811

### PR DESCRIPTION
**Pull request by sabas1080**
Hi

I am trying to add the board RAK811, I am new to this and I have followed this tutorial

https://github.com/stm32duino/wiki/wiki/Add-a-new-variant-(board)

RAK811 info:

"core": "stm32",
"cpu": "cortex-m3",
"extra_flags": "-DSTM32L151xB -DSTM32L151CBx",
"mcu": "stm32l151cbx",
"variant": "stm32l151xba",

"url": "http://www.rakwireless.com/en/download/RAK811/Hardware%20Design",
"vendor": "RAK"

stm32flash /dev/ttyUSB0
stm32flash 0.5
http://stm32flash.sourceforge.net/

Interface serial_posix: 57600 8E1
Version : 0x31
Option 1 : 0x00
Option 2 : 0x00
Device ID : 0x0429 (STM32L1xxx6(8/B)A)

RAM : 16KiB 
Flash : 128KiB (size first sector: 16x256)

Here is source,
https://github.com/RAKWireless/RAK811_BreakBoard

Datasheet:
http://wiki.rakwireless.com/lib/exe/fetch.php?media=rak811_lora_module_datasheet_v1.3.pdf

Examples of boards:
https://www.aliexpress.com/store/product/RAK811-LoRa-Tracker-Board-MAX-7Q-GPS-Module-and-MEMS-Sensor-Wireless-Remote-Positioning-Solution-LoRaWAN/2805180_32844470946.html?spm=2114.12010608.0.0.219c103eDASa9w

 Thanks
#219 
https://github.com/rogerclarkmelbourne/Arduino_STM32/issues/442

### CODE REVIEW

**Comment by fpistm** [comment]
Hi @sabas1080 ,
FLASH_BANK1_END is define by the CMSIS device file.
For this version [stm32l151xb](https://github.com/stm32duino/Arduino_Core_STM32/blob/7ee0f17911cfb34066886f61a0d1cfa10c47aedb/system/Drivers/CMSIS/Device/ST/STM32L1xx/Include/stm32l151xb.h#L584) it is not defined as few flash size.

So in stm32_eeprom.c, it require to handle this case:
https://github.com/stm32duino/Arduino_Core_STM32/blob/7ee0f17911cfb34066886f61a0d1cfa10c47aedb/cores/arduino/stm32/stm32_eeprom.c#L75

Probably like this

```
#ifdef FLASH_BANK2_END
#define FLASH_BASE_ADDRESS  ((uint32_t)((FLASH_BANK2_END + 1) - FLASH_PAGE_SIZE))
#elif defined(FLASH_BANK1_END)
#define FLASH_BASE_ADDRESS  ((uint32_t)((FLASH_BANK1_END + 1) - FLASH_PAGE_SIZE))
#else
#define FLASH_BASE_ADDRESS  ((uint32_t)((FLASH_END + 1) - FLASH_PAGE_SIZE))
#endif // FLASH_BANK2_END
```

**Comment by sabas1080** [comment]
Work ok blink, define led_built ok, Serial ok

**Comment by fpistm** [comment]
It seems you used an old version of the core to test.
For better Arduino compatibility, some pins definitions have changed.
See https://github.com/stm32duino/Arduino_Core_STM32/blob/master/variants/board_template/variant.h
ex: Analog pins is no more an enum.

RAK is not a Nucleo 64. It hink you could add a "RAK" menu and then the RAK 811

**Comment by fpistm** [comment]
This PR should be replace by this one: #254

**Comment by fpistm** [comment]
#254 merged.
Close this one.

**Pull request closed without merging**
