### PR TITLE
Add Armed v1 board variant

### PR DESCRIPTION
**Pull request by ktand**
Armed is a 3D printer controller based on STM32F407 designed to run Marlin.

### CODE REVIEW

**Comment by fpistm** [comment]
I think it should also be nice to not add a new section for this board and follow @hasenbanck recommendation in  #361:

> I took the liberty to rename the menu section "RemRam series" to "3D printer boards" to not clutter the core more than necessary (as suggested in #347).

**Comment by hasenbanck** [comment]
> I think it should also be nice to not add a new section for this board and follow @hasenbanck recommendation in #361:
> 
> > I took the liberty to rename the menu section "RemRam series" to "3D printer boards" to not clutter the core more than necessary (as suggested in #347).

So

```ini
# Armed boards
Armed.name=Armed Series
```

would become

```ini
# 3D printer boards
3dprinter.name=3D printer boards
```

I would then rebase my changes again and we wouldn't clutter the the main section more then we need.

**Comment by ktand** [comment]
No, haven't thought about that. Will check it out!

Thanks.

**Comment by ktand** [comment]
Would sharing a "3d printer" section require all boards in that section to use the save USB vid/pid?

3dprinter.build.vid=0x0483
3dprinter.build.pid=0x5711
3dprinter.vid.0=0x0483
3dprinter.pid.0=0x5711

**Comment by ktand** [comment]
> USB will be part of 1.5 based on @hasenbanck
> About pid/vid I think it could be defined per variant if needed.
> I think also we could in a first step do a separate PR to rename the `RemRam series` to `3D printer boards` to avoid any conflicts issues with PR.

Ok. @hasenbanck , do you want med to submit the PR regarding the rename or will you do it?

**Comment by hasenbanck** [comment]
@ktand I'm at work and would only have time this evening. If you are faster, then please do it yourself.

**Comment by ktand** [comment]
> @ktand I'm at work and would only have time this evening. If you are faster, then please do it yourself.

Same here.

**Comment by hasenbanck** [comment]
Found some time in the break. Here we go: #365

**Comment by ktand** [comment]
> Found some time in the break. Here we go: #365

Is there any way I can base my PR on your PR? Or do I have to wait for your PR to be merged before I can adjust mine?

**Comment by hasenbanck** [comment]
I would wait for the merge of the other PR and then do a rebase of this PR.

**Comment by fpistm** [comment]
#365 merged.

**Comment by ktand** [comment]
I have updated my PR as suggested.

**Comment by ktand** [comment]
Tweaked SPI pin definition. Ready to be merged.

**Comment by ktand** [comment]
@fpistm There is no ethernet on this board, but I can update the file to the latest version if you like.

**Comment by fpistm** [comment]
@ktand No, if no ethernet that's good.
Just this request, please ;)

> Please, could you share a link on a description of this board?
> Thanks in advance.

**Comment by ktand** [comment]
@fpistm Sorry for the delay, cleaned up project and pushed to Github. Here is the link: [Armed on Github](https://github.com/ktand/Armed/blob/master/README.md)

**Comment by hasenbanck** [comment]
I approve the usage of good fuses! Nice board design!

**Pull request merged**
