### PR TITLE
Add ldscript.ld for STM32L051K(6-8)U and -T

### PR DESCRIPTION
**Pull request by ademuri**
**Summary**

This PR adds loader scripts for the `STM32L051K(6-8)U` and `STM32L051K(6-8)T` variants. They are generated using STM32Cube, following [the documentation in the wiki](https://github.com/stm32duino/Arduino_Core_STM32/wiki/Add-a-new-variant-(board)#2---add-the-default-linker-script).

### CODE REVIEW

**Comment by fpistm** [comment]
Hi @ademuri 
Thanks for the PR, anyway it is not complete, you have to adda de fault clock config, declare the variant and add them to the README.
https://github.com/stm32duino/Arduino_Core_STM32/wiki/Add-a-new-variant-(board)#3---generic-system-clock-configuration

**Comment by fpistm** [comment]
Close it as no feedback from OP. PR not complete as stated in previous comment. Update your branch then PR can be reopened.

**Comment by ademuri** [comment]
I've updated this pull request with the other changes, and this is ready for review.

**Comment by fpistm** [comment]
No change at this time.

**Comment by ademuri** [comment]
Hmm, that's odd - I updated the branch that this PR is based on, but this PR did not update. Instead created a new pull request: https://github.com/stm32duino/Arduino_Core_STM32/pull/2405

**Pull request closed without merging**
