### PR TITLE
Add define for ARDUINO_CORE_STM32 that can be used to identify this Arduino core

### PR DESCRIPTION
**Pull request by ktand**
It would be nice if it was possible to identify this Arduino core. I have added a define for ARDUINO_CORE_STM32.

### CODE REVIEW

**Comment by fpistm** [comment]
Hi @ktand ,
in fact it already exist. Each arduino core define its own define: `-DARDUINO_ARCH_{build.arch}`
Use `ARDUINO_ARCH_STM32`

**Comment by ktand** [comment]
Hi @fpistm.

Unfortunately the [Platformio framework](https://github.com/maichaell/platform-ststm32) that has been modified for [STM32GENERIC](https://github.com/danieleff/STM32GENERIC) defines the same `ARDUINO_ARCH_STM32`. I've created a HAL for STM32F4 for the [Marlin](https://github.com/MarlinFirmware/Marlin) project using STM32GENERIC but would like to be able use this core as well. Any idea how I could identify this framework without relying on the `ARDUINO_ARCH_STM32` define?

**Comment by fpistm** [comment]
Unfortunately, I would not add new define, official one is `ARDUINO_ARCH_STM32`
This define is used in several third party libraries for this core and do not want multiply define to identify this core.

**Comment by ktand** [comment]
@fpistm I realized that STM32GENERIC defines `STM32GENERIC `so I can use that define to switch on. I will close this PR.

**Pull request closed without merging**
