### PR TITLE
Add new Thunderpack v1.1: STM32F411

### PR DESCRIPTION
**Pull request by jgillick**
**Summary**

Adds the new Thunderpack board (v1.1), which replaces the STM32L07 chip from v1 with an STM32F411.

Version 1.1 branch of the project: https://github.com/jgillick/ThunderPack/tree/STM32F4

### CODE REVIEW

**Comment by fpistm** [comment]
Hi @jgillick 
thnaks for update.
Please fix the astyle issue:
```patch
diff --git a/variants/THUNDERPACK_F411/variant.cpp b/variants/THUNDERPACK_F411/variant.cpp
index 2e1c0a2..7ea64d8 100644
--- a/variants/THUNDERPACK_F411/variant.cpp
+++ b/variants/THUNDERPACK_F411/variant.cpp
@@ -101,8 +101,8 @@ WEAK void SystemClock_Config(void)
   }
 
   // Select PLL as system clock source and configure the HCLK, PCLK1 and PCLK2 clocks dividers
-  RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK|RCC_CLOCKTYPE_SYSCLK
-                                |RCC_CLOCKTYPE_PCLK1|RCC_CLOCKTYPE_PCLK2;
+  RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK | RCC_CLOCKTYPE_SYSCLK
+                                | RCC_CLOCKTYPE_PCLK1 | RCC_CLOCKTYPE_PCLK2;
   RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_PLLCLK;
   RCC_ClkInitStruct.AHBCLKDivider = RCC_SYSCLK_DIV1;
   RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV2;
```

**Comment by fpistm** [comment]
Could you also update this file:
https://github.com/stm32duino/Arduino_Core_STM32/blob/master/CI/build/conf/cores_config.json

to ignore both THUNDERPACK as you rename one and create a new one.

Thanks.

**Comment by fpistm** [comment]
Hi @jgillick 
I've updated your branch with some fixes and also a merge of both variant.
Please, could you test on your side and give me your feedback?
Thanks

**Comment by jgillick** [comment]
@fpistm Your changes work great on both boards. I also made an additional small commit to remove an unused macro.

**Comment by fpistm** [comment]
I though you have a HSE at 24 MHz. I saw it on your schematics.
By default it is 25MHz so if it is not this value it have to be define.

**Comment by fpistm** [comment]
From [here](https://github.com/jgillick/ThunderPack/blob/STM32F4/hardware/Standard_18650/schematic.pdf)
image

And by default HSE_VALUE is 8 MHz:
https://github.com/stm32duino/Arduino_Core_STM32/blob/0f24f28ab48ce24f5a148dbace85ff86dee477ec/system/STM32F4xx/stm32f4xx_hal_conf_default.h#L98

**Comment by fpistm** [comment]
@jgillick 
any update on HSE value ?

**Comment by jgillick** [comment]
Ah, you're absolutely right, thanks for the correction I've reverted that commit.

**Comment by matthijskooijman** [comment]
@jgillick I'm working on some USB refactoring. Can you tell me if there is an external 1.5k pullup on the board? Or are you relying on the internal pullup (which would be better AFAICS)?

**Comment by fpistm** [comment]
@matthijskooijman 
I think no, there is only an ESD protection:
image

**Comment by matthijskooijman** [comment]
Ok, great! I couldn't find any schematic to confirm yesterday, but this looks good. Thanks, I'll update my commit I'm about to push accordingly.

**Comment by fpistm** [comment]
here: 

https://github.com/jgillick/ThunderPack/blob/master/hardware/Standard_18650/schematic.pdf

Even if it is F412 this is the same.

**Comment by jgillick** [comment]
Yes, that's the correct schematic. I clearly need to update the chip reference, but the rest of the circuit is the same.

**Pull request merged**
