### PR TITLE
New variant - Malyan M300 3D Printer

### PR DESCRIPTION
**Pull request by mojocorp**
This adds board support for Malyan M300 with STM32F070CBT MCU

### CODE REVIEW

**Comment by fpistm** [comment]
Hi  @mojocorp 
Thanks for this variant.
I saw you made some force pushed.
Let me know when it is OK for review.
I will not be able to test so I will consider you test it :wink: 
I guess it is used with Marlin ?

**Comment by mojocorp** [comment]
I just did some minor typo changes. I tested it with Marlin 2 and everything work, except saving the settings to flash. I don't know yet from where the problem is coming from and it will take me a lot of time. Since this variant is a variant from the M200 V2, I'm in contact with the original author. Maybe he can help me solving this issue.
Should I cancel this PR due to this know problem ?
If it's acceptable, I won't change this PR anymore and you can review it.

**Comment by fpistm** [comment]
@mojocorp 
Thanks for the feedback.
I will review the PR.
About EEPROM, no worry.

**Comment by mojocorp** [comment]
Thx for the improvements. I have to check that everything work as expected.
I'll tell you asap.

**Comment by mojocorp** [comment]
Everything work as expected!

**Comment by fpistm** [comment]
Fine. As I said you can add the pins description if you want.

**Comment by mojocorp** [comment]
> Fine. As I said you can add the pins description if you want.

I just did it.

**Comment by mojocorp** [comment]
It's certainly not the right place to comment but here it what happenend:
The M300 and M200 V2 variant are working with STM32 cores 1.7.0 but not with the current master 1.8.0-dev. The printer crashes almost immediately. I'm trying to bissect to detect which commit introduced the problem.

**Comment by fpistm** [comment]
@mojocorp 
Bad news, anyway I guess you use Marlin and so probably the Marlin needs update or you are not on the right branch of Marlin.
Maybe @LinoBarreca have some clue.

**Comment by LinoBarreca** [comment]
I wouldn't mind now since 1.8.0 hasn't been released yet and it isn't final. We will make the necessary modifications to Marlin when it's time to.

**Comment by fpistm** [comment]
@LinoBarreca 
I would just have your opinion about @mojocorp issue probably due to Marlin firmware misalignement,
Not the exact issue :wink:

**Comment by LinoBarreca** [comment]
@fpistm Yeah, I understood what you meant. Fact is that me and @sjasonsmith did some hacks to make it work with 1.7.0 while making the PRs here.
when 1.8.0 comes out we will need to revisit (take away) the hacks we did....

..or did I misunderstand what you asked?

**Comment by fpistm** [comment]
We are aligned ;)

**Comment by mojocorp** [comment]
I finally took the time to find the problem and it's due to the LTO option.
This commit in 1.8.0 introduce the problem:
fdc96bc50d7ce0a12466b256e72689a9e5f888a8  Fix usage of weak functions instead of harden one
Since the Malyan M300 has only 128k flash, the LTO option is mandatory. Is there a workaround ?

**Comment by fpistm** [comment]
@mojocorp 
LTO option is provided "as is". They are several issue on arm gcc around this so I will not able to help on this.

**Pull request merged**
