### PR TITLE
Analog pins definition clean up

### PR DESCRIPTION
**Pull request by fpistm**
This PR allows to define non contiguous analog pins.

Based on @MCUdude works.

~After several investigations, it is not possible to provide a generic way to define non contiguous analog pins.
This PR simply clean the analog pins definition~

Finally, found a way to fit all requirements.

### CODE REVIEW

**Comment by MCUdude** [comment]
Looks good to me!

**Comment by fpistm** [comment]
@MCUdude 
any feedback on my last proposal?

**Comment by MCUdude** [comment]
Sorry, I've been on a business trip for a while, but I'm back home tonight. I'll get into it in a day or two

**Comment by fpistm** [comment]
@MCUdude 
I've finish to validate and all seems OK.
If you have any feedback, this would be great 😉

**Comment by MCUdude** [comment]
Just had a quick look at the code. So this means that if `NUM_ANALOG_FIRST` is not defined, the core will use the analog pins array, and the only way to use analogRead if with the analog channel number (0..15) or the analog pin number (A0..A15). Pxy and digital pin number will not work, am I right?

**Comment by fpistm** [comment]
No it works for all

**Comment by MCUdude** [comment]
I'm trying to wrap my head around how this works, but I'm struggling. Would you like to give a short explanation of how it's able to determine the difference between:

``` c
analogRead(4); // Digital pin 4
analogRead(4); // Analog channel 4
analogRead(A4); // Analog pin 4
```

And I'll assume that the analog pins aren't reserved for analog use only?

**Comment by fpistm** [comment]
`analogRead(4); // Digital pin 4` is the same of `analogRead(4); // Analog channel 4`
Using `analogRead` implies tu use an analog pin.

**Comment by fpistm** [comment]
Using `PYn` will works as now an analog `PYn` is define as `Ax`.

**Comment by MCUdude** [comment]
OK, so analogRead will necessarily not support _Arduino digital pin numbers_ (since it may/will conflict with analog channel numbers), but rather analog channel number (0..15), analog pin number (A0..A15) and PYx.

Here's the 16 first pins of the generic F401Rx pinout. Is this the correct way of defining them?
```c
//                  | DIGITAL | ANALOG | USART     | TWI      | SPI                    | SPECIAL   |
//                  |---------|--------|-----------|----------|------------------------|-----------|
#define PA0  A0  // | 0       | A0     |           |          |                        |           |
#define PA1  A1  // | 1       | A1     |           |          |                        |           |
#define PA2  A2  // | 2       | A2     | USART2_TX |          |                        |           |
#define PA3  A3  // | 3       | A3     | USART2_RX |          |                        |           |
#define PA4  A4  // | 4       | A4     |           |          | SPI1_SS, (SPI3_SS)     |           |
#define PA5  A5  // | 5       | A5     |           |          | SPI1_SCK               |           |
#define PA6  A6  // | 6       | A6     |           |          | SPI1_MISO              |           |
#define PA7  A7  // | 7       | A7     |           |          | SPI1_MOSI              |           |
#define PA8  8   // | 8       |        |           | TWI3_SCL |                        |           |
#define PA9  9   // | 9       |        | USART1_TX |          |                        |           |
#define PA10 10  // | 10      |        | USART1_RX |          |                        |           |
#define PA11 11  // | 11      |        | USART6_TX |          |                        |           |
#define PA12 12  // | 12      |        | USART6_RX |          |                        |           |
#define PA13 13  // | 13      |        |           |          |                        | SWD_SWDIO |
#define PA14 14  // | 14      |        |           |          |                        | SWD_SWCLK |
#define PA15 15  // | 15      |        |           |          | SPI1_SS, (SPI3_SS)     |           |
```

With the following analogInPin table:
```c
// Analog (Ax) pin number array
const uint32_t analogInPin[] = {
  0,  // A0
  1,  // A1
  2,  // A2
  3,  // A3
  4,  // A4
  5,  // A5
  6,  // A6
  7,  // A7
  16, // A8
  17, // A9
  31, // A10
  32, // A11
  33, // A12
  34, // A13
  35, // A14
  36  // A15
}
```

**Comment by fpistm** [comment]
yes this is like this.

**Comment by MCUdude** [comment]
Great! I'll push some changes to #784 to reflect these changes. BTW this PR looks good to me!

**Comment by fpistm** [comment]
Firmata compatibility:
https://github.com/firmata/arduino/pull/440

**Pull request merged**
