### PR TITLE
Add LoRa pins definition for DISCO_L072CZ_LRWAN1

### PR DESCRIPTION
**Pull request by fpistm**
With this PR, the LoRa module could be used with this library:
https://github.com/sandeepmistry/arduino-LoRa

Configuration to add in arduino-LoRa example sketches:
```
  SPI.setMISO(RADIO_MISO_PORT);
  SPI.setMOSI(RADIO_MOSI_PORT);
  SPI.setSCLK(RADIO_SCLK_PORT);
  SPI.setSSEL(RADIO_NSS_PORT);
  LoRa.setPins(RADIO_NSS_PORT, RADIO_RESET_PORT, RADIO_DIO_0_PORT);
```

Note that some PR are under review for arduino-LoRa library to be able
to change the `SPI` instance used ([arduino-LoRa/#103](https://github.com/sandeepmistry/arduino-LoRa/pull/103) and [arduino-LoRa/#105](https://github.com/sandeepmistry/arduino-LoRa/pull/105) ). So, instead of changing `SPI` pins, a new instance could be created:

```
  SPIClass LoRaSPI(RADIO_MOSI_PORT, RADIO_MISO_PORT, RADIO_SCLK_PORT, RADIO_NSS_PORT);
  LoRa.setSPI(LoRaSPI);
  LoRa.setPins(RADIO_NSS_PORT, RADIO_RESET_PORT, RADIO_DIO_0_PORT);
```

### CODE REVIEW

**Comment by biagiom** [comment]
Hi @fpistm,
I think that the title of the pull request should changed in "Add LoRa pins definition for DISCO_L072CZ_LRWAN1", in fact it refers to B-L475E-IOT01A Discovery board but changes are related to DISCO_L072CZ_LRWAN.
Regards.

**Comment by fpistm** [comment]
thanks @biagiom  ;)

**Comment by biagiom** [comment]
you're welcome @fpistm !

**Comment by ucdos123456** [comment]
@fpistm sorry, can i ask is there any SSD1306 OLED example or library for  DISCO_L072CZ_LRWAN1 ?

**Comment by fpistm** [comment]
Hi,
This Issue was for Lora pins definition.
For primary support/question please enter a new topic on stm32duino.com.
Anyway, I've never tried SSD1306. Maybe you can try https://github.com/adafruit/Adafruit_SSD1306

**Pull request merged**
