### PR TITLE
USB enhancement

### PR DESCRIPTION
**Pull request by fpistm**
List:
 * [x] #410 merged (include some typos and warnings fixes)
 * [x] HID composite clean up 
 * [x] `USB_DISC_PIN` and re-enumeration --> Covered by #426
 * [x] Serial and Serial Event management --> Covered by #424
 * [x] `readBytes` and `readBytesUntil` thanks @makarenya (#410) 

Current Status:
FS well functional.
HS ok except ReadByte test.

### CODE REVIEW

**Comment by makarenya** [comment]
I'm trying to reproduce this bug, but...

python code on host:

```
import serial
ser = serial.Serial('/dev/ttyACM0', 9600, timeout=1)
for i in range(1000):
    ser.write('{}\n'.format(i).encode('utf-8'))
    s = ser.readline().strip().decode('utf-8')
    if s == str(i):
        print('Wrote: {} Read: {}'.format(i, s))
    else:
        print('Wrote: {} Read: {} Expected = {}'.format(i, s, i))
```

code on STM32F103C8T6

```
#include <Arduino.h>
#include "USBSerial.h"

void setup()
{
  SerialUSB.begin(250000);
  pinMode(LED_BUILTIN, OUTPUT);
}

void loop()
{
  if (SerialUSB.available() > 0)
  {
    String s=SerialUSB.readStringUntil('\n');
    SerialUSB.print(s+'\n');
    digitalToggle(LED_BUILTIN);
  }
}
```
same as yours, except it uses '\n' instead of '\r'

And it produces no errors at all. On the STM32F103...
Today, my STM32F407 board makes a fascinating journey through the vast expanses of China and Russia, on the broken wings of the postal services of these countries, and I can test it only in a month or two...

**Comment by makarenya** [comment]
I think I know the answer. The fact is that a prerequisite for flawless operation is that the `USBD_CDC_TransmitPacket method (& hUSBD_Device_CDC);` on `cores/arduino/stm32/usb/cdc/usbd_cdc_if.c:259` will write all the data transferred to it to the allocated memory at once. But in fact, he is not obliged to do this! It will only do this if the size of the transferred data is less than the size of the endpoint buffer, and this is at least 100% true for FS!

**Comment by makarenya** [comment]
I will read the code for STM32F407 today and see what and where bugs could have been generated.

**Comment by RickKimball** [comment]
Has anyone tried the teensy test code? https://www.pjrc.com/teensy/benchmark_usb_serial_receive.html . It might be useful to see how this code compares to other boards

**Comment by BennehBoy** [comment]
@RickKimball I, and others, tried it on the parent USB PR #388: speeds were similar to above.

**Comment by fpistm** [comment]
@RickKimball yes, this is how we bench the speed. Anyway, I will try to find/implement a test for send and also check data integrity.

**Comment by makarenya** [comment]
All errors are fixed, PR are updated!

**Comment by makarenya** [comment]
Can someone share a speed test? It's interesting to try double buffering and generally look at USB optimization options.

**Comment by fpistm** [comment]
Thanks @makarenya. I will test it tomorrow. Currently I do not have a full speed test. We only use the one from PJRC. https://www.pjrc.com/teensy/benchmark_usb_serial_receive.html

**Comment by fpistm** [comment]
I've added @makarenya fixes. Thanks ;)
HS speed test seems now functional even if speed seems impacted (Previous: 3915181, now 1897899).
FS has the same speed.
I've only made speed test no data integrity.

**Comment by makarenya** [comment]
I can try to speed up it on f103 board (it has endpoint double buffering feature, that **must** speed it up). But i today i have no other stm32 boards... however i bough f407 and am waiting for the postal service

**Comment by BennehBoy** [comment]
Happy to test any f4 speed improvements here...

**Comment by ktand** [comment]
I'm also happy to test any F4 speed improvments.

Maybe one optimization would be to implement the readBytes() function as done in Teensyduino?  (ref [USB Virtual Serial Receive Speed](https://www.pjrc.com/teensy/benchmark_usb_serial_receive.html))

**Comment by fpistm** [comment]
Yes, of course. This is in the liste. Forgot to list it.

**Comment by makarenya** [comment]
[#410](https://github.com/stm32duino/Arduino_Core_STM32/pull/410) updated, added bulk readBytes method and some other small speed improvements. Can you test it?

**Comment by fpistm** [comment]
Thanks @makarenya 
I will test it this afternoon

**Comment by fpistm** [comment]
I've updated the PR with @makarenya speed improvements.
My first tests show that speed is a bit better.
I'm currently not succeeded to use readBytes() with the PJRC tests. :(

**Comment by makarenya** [comment]
What exactly is wrong with HS?

**Comment by fpistm** [comment]
Using PJRC ReadBytes test, on linux and mac speed seems very high and not coherent
with Disco F746NG:
* Linux 16192811
* Mac 6691058
* Windows:
```
ignoring startup buffering...
ignoring startup buffering...
ignoring startup buffering...
ignoring startup buffering...
ignoring startup buffering...
Bytes per second = 3845907
Bytes per second = 1
Bytes per second = 3846154
Bytes per second = 1
Bytes per second = 3846154
Bytes per second = 3846154
Bytes per second = 1
Bytes per second = 3846154
Bytes per second = 1
Bytes per second = 3845907
Bytes per second = 1
Bytes per second = 3846154
Bytes per second = 1
Bytes per second = 3846154
Bytes per second = 1
Average bytes per second = 1
```
If I use the ReadBytes with overhead test, it seems correct:
* Linux 977794	
* Mac 929056	
* Windows 961526

**Comment by BennehBoy** [comment]
Can the HID magic word code from usb_cdc_if.cpp be incorporated into this pull?  -> https://github.com/stm32duino/Arduino_Core_STM32/pull/415/files#diff-e573591f370c1c541235d601d8e9dd2cR63

Would remove much rebasing over there and should not be too invasive.

Similarly, here was the rough and ready DISC pin handling (hardcoded on PB9 for maple mini) -> https://github.com/stm32duino/Arduino_Core_STM32/pull/415/files#diff-0cee7a00a7b90767ce1a665fb99bc99cR64

**Comment by fpistm** [comment]
This would be nice you made a proper commit for each features and explain goal. (Not for the USB DISC pin, I will manage it)
You can do it on top of my branch, simply add my fork on you remote list:
```
git remote add fpistm https://github.com/fpistm/Arduino_Core_STM32
git fetch fpistm
```
then create your topic branch on top of mys USB_enhancement branch.
Like this you could do a PR on my fork .

**Comment by BennehBoy** [comment]
OK Will do.

**Comment by BennehBoy** [comment]
You've probably seen this already, but the above is done, here - https://github.com/fpistm/Arduino_Core_STM32/pull/5

**Comment by fpistm** [comment]
Yes I saw @BennehBoy 
I will have to review it.
Note that I've made a PR for re-numeration which seems works well and also manage USB_DISC_PIN (#426)
For those who want to test I've made a branch including all USB relasted PR: #419 / #424  / #426 
https://github.com/fpistm/Arduino_Core_STM32/tree/USB_PR_419_424_426

**Comment by fpistm** [comment]
Ok. Thanks @BennehBoy ,
I think I will merge those PR then release the 1.5.0.
It seems enough stable.

**Comment by BennehBoy** [comment]
HID bootloader works fine.

DFU with Maple Original bootloader works fine - DISC PIN handling working.

Seems good to me.

Will you consider merging HID/DFU & the magic word handling also?

**Comment by makarenya** [comment]
Got it, i make it tomorrow

**Comment by ktand** [comment]
Hi @makarenya 

Did you find a solution to the problem with writes to the CDC when the port is not opened on the host side? If you need any help testing just let me know.

**Comment by fpistm** [comment]
@BennehBoy, @ktand could you test this latest version, please?
Thanks in advance.
@BennehBoy this should solve issue you met with bootloader.
@ktand I don't think this solved your issue anyway USB is init earlier.

I will do a release this week, so hope to solve your issue with Marlin before.

**Comment by BennehBoy** [comment]
@fpistm - works 👍

**Comment by ktand** [comment]
@fpistm I will test tonight.

Den tis 12 feb. 2019 22:27Ben Anderson <notifications@github.com> skrev:

**Comment by fpistm** [comment]
I think I will merge this PR.
New PR could be opened to solve issue related to Marlin before the release or this will be available in the next one.

**Pull request merged**
