### PR TITLE
Add support of BlackPill F303CC

### PR DESCRIPTION
**Pull request by fpistm**
## Board:
https://robotdyn.com/stm32f303cct6-256-kb-flash-stm32-arm-cortexr-m4-mini-system-dev-board-3326a9dd-3c19-11e9-910a-901b0ebb3621.html

### CODE REVIEW

**Comment by BennehBoy** [comment]
Thanks @fpistm 

I posted this over on the forums:

> I was just thinking about how these 'PILL' style boards should be handled in the official core, there's a fair bit of fragmentation in the variants folder currently, the BLUEPILL_F103XX folder handles generic blue & blackpills (and robotdyns board), Sparky V1 handles the F303CC, and currently there's nothing for the F401...
> 
> I might submit a PR which does he following:
> 
> F103 based boards - rename BLUEPILL_F103XX to PILL_F103XX
> F401 based boards - create PILL_F401XX variant
> F303 based boards - create PILL_F303XX variant, essentially the Sparky V1 but with standard usart mapping
> 
> I wonder whether it would be also worth creating 'GENERIC' variants which simply have the basefunctionality all enabled - of course anyone wishing to have Arduino style pin mapping would be playing pot luck if they were looping over the pins. This would make it much simpler for people to get up and running with new boards - albeit with potential issues for board specific peripherals.

link here -> https://www.stm32duino.com/viewtopic.php?p=54755#p54755

Thoughts?

**Comment by BennehBoy** [comment]
ps, boards.txt refers to Black407VE - copy paste error I guess?

```
# Black F407VE
GenF3.menu.pnum.BLACKPILL_F303XX=BlackPill F303CC
```

**Comment by fpistm** [comment]
@BennehBoy,
I've already answered you 😄 
I've already made the variant so don't rename it.
Anyway this is a PR, so under review and wait your comments :)
For `boards.txt `right copy/paste... nice shot 😉

**Comment by BennehBoy** [comment]
> @BennehBoy,
> I've already answered you 

So you did - missed that :blush:

**Comment by RickKimball** [comment]
Have you given any thought to putting the ISR routine code into CCMRAM?

**Comment by fpistm** [comment]
> Have you given any thought to putting the ISR routine code into CCMRAM?

Honestly no, do not hesitate to share with us 😉

**Comment by RickKimball** [comment]
It would require some startup code changes.  The only part missing is to copy *.ccmram from flash to ccmram at startup. Something like this:
```
$ ls system/Drivers/CMSIS/Device/ST/STM32F3xx/Source/Templates/gcc/startup_stm32f303xc*
system/Drivers/CMSIS/Device/ST/STM32F3xx/Source/Templates/gcc/startup_stm32f303xc_ccmram.s
system/Drivers/CMSIS/Device/ST/STM32F3xx/Source/Templates/gcc/startup_stm32f303xc.s
$ diff system/Drivers/CMSIS/Device/ST/STM32F3xx/Source/Templates/gcc/startup_stm32f303xc*
78,94d77
< /* Copy the ccmram segment initializers from flash to SRAM */
<   movs	r1, #0
<   b	LoopCopyCCMRamInit
< 
< CopyCCMRamInit:
< 	ldr	r3, =_siccmram
< 	ldr	r3, [r3, r1]
< 	str	r3, [r0, r1]
< 	adds	r1, r1, #4
< 
< LoopCopyCCMRamInit:
< 	ldr	r0, =_sccmram
< 	ldr	r3, =_eccmram
< 	adds	r2, r0, r1
< 	cmp	r2, r3
< 	bcc	CopyCCMRamInit
< 
113d95
< 
```
Then for any routine you want to run from CCMRAM, you just give it the attribute.

I guess this is probably best left as an exercise to the user.  It would probably be better if it was done on a sketch by sketch basis. ... so .. never mind ... :)

**Comment by fpistm** [comment]
Thanks @RickKimball 

Maybe you can add this as an example here: 
https://github.com/stm32duino/wiki/wiki/Custom-definitions#custom-startup-file

**Comment by BennehBoy** [comment]
Tested this variant with a RobotDyn F303CC BlackPill, SPI & CDC confirmed working - will do further testing later.

**Comment by RickKimball** [comment]
Placing these boards under the Generic STM32F3 is fine. However calling it a blackpillf303cc seems to be confusing if you haven't been reading the stm32duino.com forum.

Would it be better to identify this board by the name that RobotDyn calls it? One their website it is labeled as: "STM32 ARM Cortex®-M4 Mini System Dev.board"

Maybe we use something like "RobotDyn Cortex-M4 Mini System Dev Board" ? This way we don't have to answer questions about how to use the board with the ST core?  Or at least have RobotDyn in the menu selection someplace so it is apparent?

**Comment by RickKimball** [comment]
Regarding naming. Why does Sparky V1 rate as a top level board?  Shouldn't there be a collection of "Flight Controller Board" ? And the RAKWireless? It also rates a top level board. Why not a collection of "Wireless Boards" ?

**Comment by fpistm** [comment]
@RickKimball 
About board name, probably, yes as robotdyn is the manufacturer. I will update the name displayed with "RobotDyn Cortex-M4 Mini System Dev Board". 

About Sparky, I've made the same comment during the PR review:
https://github.com/stm32duino/Arduino_Core_STM32/pull/432#issuecomment-462247973
As I don't know the flight controller ecosystem, I followed his comment.

About RAK, as there are several RAK boards, I added them under their site name.
https://www.rakwireless.com/en/.
So why not, maybe it could be renamed later if new wireless board is added 😆

**Comment by RickKimball** [comment]
Wait!

I was just chatting with the sales agent at RobotDyn. I asked if they had a preferred name and they went and asked Chief Executive Shavkat Begishev. The official name they prefer "RobotDyn Blackpill F303"

**Comment by fpistm** [comment]
Don't worry, I will do update later. 
Any comment are welcome ;)

**Comment by fpistm** [comment]
I've updated the name.
I have to made a new release to fix an issue with the arm none eabi gcc toolchain on windows.
So I think to merge this variant to add it to the release.
Do you see any blocker for this ?

**Comment by BennehBoy** [comment]
No blockers that I can see, is the gcc fix for  windows paths with spaces?

**Comment by fpistm** [comment]
> 
> No blockers that I can see, is the gcc fix for windows paths with spaces?

yes.

**Comment by Alteregoxxx** [comment]
Sorry if this is not the right place for my question: it seems, reading from the PlatformIO documentation, that DFU upload method is not yet supported for this board/MCU, am I wrong?

If I'm right, in the hope to grasp the concepts behind usb DFU, can I kindly ask why? I mean,  AN2606 ([https://www.st.com/content/ccc/resource/technical/document/application_note/b9/9b/16/3a/12/1e/40/0c/CD00167594.pdf/files/CD00167594.pdf/jcr:content/translations/en.CD00167594.pdf](url)) says STM32F303xB(C) has USB bootloader pre-burned in factory and, in my base understanding, having an utility like DFU-util that, still in my base understanding, we already use for boards like BluepillF103Cx, should be sufficient to complete the "recipe", no? What am I missing? Could you point me on some "basic" info source?

I would really like to gain some knowledge on the topic and, maybe, help someday :-)

**Comment by fpistm** [comment]
@Alteregoxxx 
This is supported, under Arduino IDE select STM32CubeProgrammer (DFU).
You have to apply the correct boot pattern before to switch in STM32 Bootloader mode.

I currently working to automatically switch to the STM32 Bootloader mod. See #710.

**Comment by Alteregoxxx** [comment]
> @Alteregoxxx
> This is supported, under Arduino IDE select STM32CubeProgrammer (DFU).

I see...
So, Arduino IDE support DFU on this chip (and probably other...)making use of the STM32CubeProgrammer software, did I get it right?
However, being a PlatformIO user, just for the sake of a better understanding, can DFU-util (that should be the DFU utility used by PlatformIOif I'm not wrong) be used for the same goal? 

> You have to apply the correct boot pattern before to switch in STM32 Bootloader mode.

Yep, I've already learned that some time ago, reading trough a few of the "brief" STM32 datasheets :-D

> I currently working to automatically switch to the STM32 Bootloader mod. See #710.

That would be great, not great as having DFU already supported in PlatformIO, but still great :-P

**Comment by fpistm** [comment]
> However, being a PlatformIO user, just for the sake of a better understanding, can DFU-util (that should be the DFU utility used by PlatformIOif I'm not wrong) be used for the same goal?

Yes DFU util could be used. About PIO, I'm not aware how  the STM32 core is integrated nor the upload tools.

**Pull request merged**
