### PR TITLE
Update to latest F4, F7 firmware and USB host/device middleware

### PR DESCRIPTION
**Pull request by fpistm**
This PR was generated thanks the script to update HAL drivers and CMSIS devices from the STM32Cube GitHub release #1026 

- F2 --> #1059
- ~Update F2 HAL from version 1.2.3 to 1.2.4~
- ~Update F2 CMSIS from version 2.2.2 to 2.2.3~
- ~Apply 1 patch for F2~
- Update F4 HAL from version 1.7.7 to 1.7.8
- Update F4 CMSIS from version 2.6.4 to 2.6.5
- Update F4 wrapped files
- Apply 2 patches for F4
- Update F7 HAL from version 1.2.7 to 1.2.8
- Update F7 CMSIS from version 1.2.4 to 1.2.5
- G4 --> #1049
- ~Update G4 HAL from version 1.1.0 to 1.1.1~ 
-  ~Update G4 CMSIS from version 1.1.0 to 1.1.1~
- H7 --> #1060 
- ~Update H7 HAL from version 1.7.0 to 1.8.0~
- ~Update H7 CMSIS from version 1.7.0 to 1.8.0~
- L4 --> #1058 
- ~Update L4 HAL from version 1.11.0 to 1.11.1~
- ~Update L4 CMSIS from version 1.6.0 to 1.6.1~
- WB --> #1057
- ~Update WB HAL from version 1.4.0 to 1.5.0~
- ~Update WB CMSIS from version 1.3.0 to 1.4.0~
- ~Update WB wrapped files~
- USB Device library to v2.6.0
- USB Host library to v3.3.4

### CODE REVIEW

**Comment by stas2z** [comment]
Are you also  going to update freertos repo to 10.2.1 shipped with latest cube update?

**Comment by fpistm** [comment]
Hi @stas2z 
this will be done later. Currently, I'm focus to release the 1.9.0.
FreeRtos is a third party library.

**Comment by fpistm** [comment]
This PR will be divided by series to ease merge.

G4 update has been moved to #1049

**Comment by qasemsherfi** [comment]
درای تراکنش از سیستم اتوماتیک  استفاده کنید

**Pull request merged**
