### PR TITLE
Add RAK811 LoRa Tracker Board

### PR DESCRIPTION
**Pull request by fpistm**
Hi @sabas1080,
This PR is the review of your PR #229
I've made several clean and rename the variant RAK811_TRACKER.
RAK811 is a module not really a board but as you mentioned in your PR the board is the 
[RAK811 LoRa Tracker](https://www.aliexpress.com/store/product/RAK811-LoRa-Tracker-Board-MAX-7Q-GPS-Module-and-MEMS-Sensor-Wireless-Remote-Positioning-Solution-LoRaWAN/2805180_32844470946.html?spm=2114.12010608.0.0.219c103eDASa9w)

 ~~I've only one doubt about RAM size 16k or 32k? I think it is 32k, could you confirm?~~ --> Sub menu added to be able to select RAM Size  (16Kb by default)

Could you test this variant and let me know if it  is ok?
Thanks in advance.

Datasheet:
http://docs.rakwireless.com/en/RAK811%20TrackerBoard/Software%20Development/RAK811%20TrackerBoard%20Datasheet%20V1.1.pdf

Github:
https://github.com/RAKWireless/RAK811_BreakBoard

Using RAK 811 Lora Module
Datasheet:
http://docs.rakwireless.com/en/RAK811/Software%20Development/RAK811%C2%A0Lora%C2%A0Module%C2%A0Datasheet%C2%A0V1.3.pdf

http://www.rakwireless.com/en/download/RAK811/Hardware%20Design

### CODE REVIEW

**Comment by fpistm** [comment]
Ok. Thanks. updated to 16kb of RAM. I read somewhere it was up to 32k maybe a mistake...
You could check with STLink how many RAM the board has really.
Let me know if it is ok.

**Comment by chaolue** [comment]
@fpistm,

May need to research the SRAM size - see https://github.com/Ebiroll/RAK811_BreakBoard

> The earlier versions of the board only had 16K ram so stm32l15xx6.ld is default as linker script. If you want to use the full 32K ram you can change this line before copy "ldscript": "/home/olof/rak/STM32L151XBA_FLASH.ld"

**Comment by fpistm** [comment]
@chaolue yes this is what I've read  👍 Maybe I could add a menu to select ramsize.
@sabas1080 have you tested ?

**Comment by fpistm** [comment]
I've added a sub menu to be able to select RAM Size  (16Kb by default)

**Comment by fpistm** [comment]
Any news @sabas1080?
I will do a release soon so if this is tested, I could merge and release it.
Thanks in advance

**Comment by sabas1080** [comment]
Hi @fpistm 

I am useing stm32flash and it appears the next information

```
Using Parser : Raw BINARY
Interface serial_posix: 115200 8E1
Version      : 0x31
Option 1     : 0x00
Option 2     : 0x00
Device ID    : 0x0429 (L1xxx6(8/B)A)
- RAM        : 32KiB  (4096b reserved by bootloader)
- Flash      : 128KiB (sector size: 16x256)
- Option RAM : 16b
- System RAM : 4KiB
```

**Comment by fpistm** [comment]
Hi @sabas1080,
without feedback from you I could not merge it.
So, without news, it will not be in next release 1.3.0

**Comment by fpistm** [comment]
@sabas1080 Any update?

**Comment by sabas1080** [comment]
I'm going to testing today

**Comment by sabas1080** [comment]
I have the next error

`/Arduino15/packages/STM32/hardware/stm32/tools/macosx/serial_upload": error=2, No such file or directory`

the path correct is

`/Users/sabas/Library/Arduino15/packages/STM32/hardware/tools`

**Comment by sabas1080** [comment]
I have updated to 1.3.0 and

`/Library/Arduino15/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32/low_power.c: In function 'LowPower_EnableWakeUpPin':
/Library/Arduino15/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32/low_power.c:98:12: error: 'SYS_WKUP1' undeclared (first use in this function)
       case SYS_WKUP1 :
            ^~~~~~~~~
/Library/Arduino15/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32/low_power.c:98:12: note: each undeclared identifier is reported only once for each function it appears in
/Library/Arduino15/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32/low_power.c:108:12: error: 'SYS_WKUP2' undeclared (first use in this function)
       case SYS_WKUP2 :
            ^~~~~~~~~
/Library/Arduino15/packages/STM32/hardware/stm32/1.3.0/cores/arduino/stm32/low_power.c:118:12: error: 'SYS_WKUP3' undeclared (first use in this function)
       case SYS_WKUP3 :
            ^~~~~~~~~
exit status 1
Error compilando para la tarjeta RAKWireless.`

**Comment by fpistm** [comment]
Sounds strange as I've added the PinNamesVar.h
https://github.com/stm32duino/Arduino_Core_STM32/pull/254/files#diff-5ad876594d46b421d0d4c00eb77e42d8

**Comment by sabas1080** [comment]
it seems to be a path error

**Comment by fpistm** [comment]
So the build is ok but it do not fin the uploader tools.
This is due to your install to use git.
https://github.com/stm32duino/wiki/wiki/Using-git-repository#3-hereafter-2-methods-to-use-git-repository
When using git depending on how and where you put the core you have to update the platform.txt.

**Comment by fpistm** [comment]
Yes.  How do you use the core git repo ?

**Comment by fpistm** [comment]
Note: I've updated Serial menu which has been changed in the last core version.

**Comment by sabas1080** [comment]
`
Mass erase failed. Try specifying the number of pages to be erased.
Failed to erase memory
stm32flash Arduino_STM32_0.9

http://github.com/rogerclarkmelbourne/arduino_stm32

Using Parser : Raw BINARY
Interface serial_posix: 115200 8E1
Version      : 0x31
Option 1     : 0x00
Option 2     : 0x00
Device ID    : 0x0429 (L1xxx6(8/B)A)
- RAM        : 32KiB  (4096b reserved by bootloader)
- Flash      : 128KiB (sector size: 16x256)
- Option RAM : 16b
- System RAM : 4KiB
Write to memory
Erasing memory
Ha ocurrido un error mientras se enviaba el sketch

`

**Comment by fpistm** [comment]
I do not changed tools binaries. So, if it's work before this should always work.

**Comment by sabas1080** [comment]
Is the version of the binary

My version is 

```
stm32flash 0.5

http://stm32flash.sourceforge.net/
```

**Comment by fpistm** [comment]
To sum up: build is ok but you cannot flash thanks Serial?
As said there is no change around flash tools. So, if it is ok before I guess this is linked to the board config to ba able to flash through Serial. Bootloader issue ?

**Comment by sabas1080** [comment]
Build ok, but stmflash version not compatible with chip

**Comment by fpistm** [comment]
Ok so you never flash using stm32flash provided with core tools before?

Regarding stm32flash source:
```
	/* L1 */
	{0x416, "STM32L1xxx6(8/B)"                , 0x20000800, 0x20004000, 0x08000000, 0x08020000, 16, p_256 , 0x1FF80000, 0x1FF8001F, 0x1FF00000, 0x1FF01000, F_NO_ME},
	{0x429, "STM32L1xxx6(8/B)A"               , 0x20001000, 0x20008000, 0x08000000, 0x08020000, 16, p_256 , 0x1FF80000, 0x1FF8001F, 0x1FF00000, 0x1FF01000, 0},
	{0x427, "STM32L1xxxC"                     , 0x20001000, 0x20008000, 0x08000000, 0x08040000, 16, p_256 , 0x1FF80000, 0x1FF8001F, 0x1FF00000, 0x1FF02000, 0},
	{0x436, "STM32L1xxxD"                     , 0x20001000, 0x2000C000, 0x08000000, 0x08060000, 16, p_256 , 0x1FF80000, 0x1FF8009F, 0x1FF00000, 0x1FF02000, 0},
	{0x437, "STM32L1xxxE"                     , 0x20001000, 0x20014000, 0x08000000, 0x08080000, 16, p_256 , 0x1FF80000, 0x1FF8009F, 0x1FF00000, 0x1FF02000, F_NO_ME},
```

`Device ID    : 0x0429 (L1xxx6(8/B)A)` is supported.

Have you selected 32kb in the RAM menu? To use the correct linker script as it seems you have `- RAM        : 32KiB  (4096b reserved by bootloader)`

There is one issue around L1 on stm32flash:
https://sourceforge.net/p/stm32flash/tickets/92/

I will try to try stm32flash on L1 to see if I reproduce your issue.

Anyway could you test with ST-Link to validate the variant?

**Comment by sabas1080** [comment]
Now that I remember, I am using this correction

https://github.com/Formlabs/stm32flash/commit/8c4aa650bffaf98e96d1b6065ab6e76c43150d8a

**Comment by sabas1080** [comment]
Yes, it should build STM32flash with this fix
Working variant blink and serial

**Comment by sabas1080** [comment]
I have an error with next code

```
void setup() {
    pinMode(LED_BUILTIN,OUTPUT);//PB_6  //CRF3
    delay(200);
    digitalWrite(LED_BUILTIN,HIGH);
    delay(500);
    digitalWrite(LED_BUILTIN,LOW);
    delay(500); 
    
}

void loop() {

}
```
led stays on

**Comment by fpistm** [comment]
If the LED is connected to 3.3V, putting LOW on the pin set the LED ON.

Ex on the DISCO L475 IOT:
discoiotled

Putting LOW set the LD4 on

**Comment by sabas1080** [comment]
Yes, LED is connected to 3.3v

**Comment by fpistm** [comment]
So this is normal :)

**Comment by fpistm** [comment]
About STM32Flash issue.
There will be 2 solutions:
1- Update it with the Fix and rebuild all host OS binaries (Windows/linux/Mac)
2- Unified tools used to flash. It should be possible to use STM32CubeProgrammer CLI. See https://github.com/stm32duino/Arduino_Tools/issues/23

Think the 2nd is the best solution as it support all STM32 Series.

**Comment by sabas1080** [comment]
I'm going to try the second option

**Comment by sabas1080** [comment]
I'm trying with STM32CubeProgrammer and i have error de protection
captura de pantalla 2018-07-16 a la s 11 40 04


```
10:16:49 : Serial Port cu.SLAB_USBtoUART is successfully opened.
10:16:49 : Sending init command: 
10:16:49 : byte 0x7F sent successfully to target
10:16:49 : Received response from target: 0x79
10:16:49 : Activating device: OK
10:16:49 : Sending GetID command and its XOR:
10:16:49 : byte 0x02 sent successfully to target
10:16:49 : byte 0xFD sent successfully to target
10:16:49 : Received response from target: 0x79
10:16:49 : Received response from target: 0x01042979
10:16:49 : Chip ID: 0x429 
10:16:49 : Sending Get command and its XOR:
10:16:49 : byte 0x00 sent successfully to target
10:16:49 : byte 0xFF sent successfully to target
10:16:49 : Received response from target: 0x79
10:16:49 : Received response from target: 0x0b
10:16:49 : size of bytes in the response: 11
10:16:49 : Received response from target: 0x31000102112131446373829279
10:16:49 : Full received response: 0b31000102112131446373829279
10:16:49 : byte 0x11 sent successfully to target
10:16:49 : byte 0xEE sent successfully to target
10:16:49 : data sent successfully to target: 0x08000000
10:16:49 : byte 0x08 sent successfully to target
10:16:49 : byte 0x00 sent successfully to target
10:16:49 : byte 0xFF sent successfully to target
10:16:49 : Sending GetID command and its XOR:
10:16:49 : byte 0x02 sent successfully to target
10:16:49 : byte 0xFD sent successfully to target
10:16:49 : Received response from target: 0x79
10:16:49 : Received response from target: 0x01042979
10:16:49 : byte 0x11 sent successfully to target
10:16:49 : byte 0xEE sent successfully to target
10:16:49 : data sent successfully to target: 0x08000000
10:16:49 : byte 0x08 sent successfully to target
10:16:49 : byte 0x00 sent successfully to target
10:16:49 : byte 0xFF sent successfully to target
10:16:49 : Sending Read command and its XOR:
10:16:49 : byte 0x11 sent successfully to target
10:16:49 : byte 0xEE sent successfully to target
10:16:49 : Received response from target: 0x79
10:16:49 : Sending Read address and its checksum:
10:16:49 : data sent successfully to target: 0x40023c1c
10:16:49 : byte 0x62 sent successfully to target
10:16:49 : Received response from target: 0x79
10:16:49 : Sending number of bytes to be read - 1 and its checksum:
10:16:49 : data sent successfully to target: 0x03
10:16:49 : byte 0xFC sent successfully to target
10:16:49 : Received response from target: 0x1f
10:16:49 : Error: Number of bytes to be be read at address: 0x40023C1C not acknowledged!
10:16:49 : Sending Read command and its XOR:
10:16:49 : byte 0x11 sent successfully to target
10:16:49 : byte 0xEE sent successfully to target
10:16:49 : Received response from target: 0x1f
10:16:49 : Error: READ command not acknowledged at address: 0x40023C1C
10:16:49 : byte 0x11 sent successfully to target
10:16:49 : byte 0xEE sent successfully to target
10:16:49 : data sent successfully to target: 0x08000000
10:16:49 : byte 0x08 sent successfully to target
10:16:53 : Disabling memory Read Protection...
10:16:53 : Sending read unprotect command and its XOR:
10:16:53 : byte 0x92 sent successfully to target
10:16:53 : byte 0x6D sent successfully to target
10:16:53 : Received response from target: 0x1f
10:16:53 : Error: Disabling memory Read Protection failed
10:17:09 : Serial Port cu.SLAB_USBtoUART is successfully opened.
10:17:09 : Sending init command: 
10:17:09 : byte 0x7F sent successfully to target
10:17:09 : Received response from target: 0x1f
10:17:09 : Error: Activating device: KO. Please, verify the boot mode configuration and check the serial port configuration. Reset your device then try again... 
10:17:17 : Serial Port cu.SLAB_USBtoUART is successfully opened.
10:17:17 : Sending init command: 
10:17:17 : byte 0x7F sent successfully to target
10:17:18 : No response from target received
10:17:18 : Error: Activating device: KO. Please, verify the boot mode configuration and check the serial port configuration. Reset your device then try again... 
10:17:21 : Serial Port cu.SLAB_USBtoUART is successfully opened.
10:17:21 : Sending init command: 
10:17:21 : byte 0x7F sent successfully to target
10:17:21 : Received response from target: 0x1f
10:17:21 : Error: Activating device: KO. Please, verify the boot mode configuration and check the serial port configuration. Reset your device then try again... 
10:18:34 : Read File: /Users/sabas/Documents/proyectoshd/RAK811WithCoreArduino/ttn/ttn.ino.RAK811.hex
10:18:34 : Number of segments: 1
10:18:34 : segment[0]: address= 0x8000000, size= 0x80C4
10:18:49 : Serial Port cu.SLAB_USBtoUART is successfully opened.
10:18:49 : Sending init command: 
10:18:49 : byte 0x7F sent successfully to target
10:18:50 : No response from target received
10:18:50 : Error: Activating device: KO. Please, verify the boot mode configuration and check the serial port configuration. Reset your device then try again... 
10:18:59 : Serial Port cu.SLAB_USBtoUART is successfully opened.
10:18:59 : Sending init command: 
10:18:59 : byte 0x7F sent successfully to target
10:18:59 : Received response from target: 0x79
10:18:59 : Activating device: OK
10:18:59 : Sending GetID command and its XOR:
10:18:59 : byte 0x02 sent successfully to target
10:18:59 : byte 0xFD sent successfully to target
10:18:59 : Received response from target: 0x79
10:18:59 : Received response from target: 0x01042979
10:18:59 : Chip ID: 0x429 
10:18:59 : Sending Get command and its XOR:
10:18:59 : byte 0x00 sent successfully to target
10:18:59 : byte 0xFF sent successfully to target
10:18:59 : Received response from target: 0x79
10:18:59 : Received response from target: 0x0b
10:18:59 : size of bytes in the response: 11
10:18:59 : Received response from target: 0x31000102112131446373829279
10:18:59 : Full received response: 0b31000102112131446373829279
10:18:59 : byte 0x11 sent successfully to target
10:18:59 : byte 0xEE sent successfully to target
10:18:59 : data sent successfully to target: 0x08000000
10:18:59 : byte 0x08 sent successfully to target
10:18:59 : byte 0x00 sent successfully to target
10:18:59 : byte 0xFF sent successfully to target
10:18:59 : Sending GetID command and its XOR:
10:18:59 : byte 0x02 sent successfully to target
10:18:59 : byte 0xFD sent successfully to target
10:18:59 : Received response from target: 0x79
10:18:59 : Received response from target: 0x01042979
10:18:59 : byte 0x11 sent successfully to target
10:18:59 : byte 0xEE sent successfully to target
10:18:59 : data sent successfully to target: 0x08000000
10:18:59 : byte 0x08 sent successfully to target
10:18:59 : byte 0x00 sent successfully to target
10:18:59 : byte 0xFF sent successfully to target
10:18:59 : Sending Read command and its XOR:
10:18:59 : byte 0x11 sent successfully to target
10:18:59 : byte 0xEE sent successfully to target
10:18:59 : Received response from target: 0x79
10:18:59 : Sending Read address and its checksum:
10:18:59 : data sent successfully to target: 0x40023c1c
10:18:59 : byte 0x62 sent successfully to target
10:18:59 : Received response from target: 0x79
10:18:59 : Sending number of bytes to be read - 1 and its checksum:
10:18:59 : data sent successfully to target: 0x03
10:18:59 : byte 0xFC sent successfully to target
10:18:59 : Received response from target: 0x1f
10:18:59 : Error: Number of bytes to be be read at address: 0x40023C1C not acknowledged!
10:18:59 : Sending Read command and its XOR:
10:18:59 : byte 0x11 sent successfully to target
10:18:59 : byte 0xEE sent successfully to target
10:18:59 : Received response from target: 0x1f
10:18:59 : Error: READ command not acknowledged at address: 0x40023C1C
10:18:59 : byte 0x11 sent successfully to target
10:18:59 : byte 0xEE sent successfully to target
10:18:59 : data sent successfully to target: 0x08000000
10:18:59 : byte 0x08 sent successfully to target
10:19:01 : Disabling memory Read Protection...
10:19:01 : Sending read unprotect command and its XOR:
10:19:01 : byte 0x92 sent successfully to target
10:19:01 : byte 0x6D sent successfully to target
10:19:01 : Received response from target: 0x1f
10:19:01 : Error: Disabling memory Read Protection failed
10:19:08 : Serial Port cu.SLAB_USBtoUART is successfully opened.
10:19:08 : Sending init command: 
10:19:08 : byte 0x7F sent successfully to target
10:19:08 : Received response from target: 0x1f
10:19:08 : Error: Activating device: KO. Please, verify the boot mode configuration and check the serial port configuration. Reset your device then try again... 
10:19:16 : Serial Port cu.SLAB_USBtoUART is successfully opened.
10:19:16 : Sending init command: 
10:19:16 : byte 0x7F sent successfully to target
10:19:16 : Received response from target: 0x79
10:19:16 : Activating device: OK
10:19:16 : Sending GetID command and its XOR:
10:19:16 : byte 0x02 sent successfully to target
10:19:16 : byte 0xFD sent successfully to target
10:19:16 : Received response from target: 0x79
10:19:16 : Received response from target: 0x01042979
10:19:16 : Chip ID: 0x429 
10:19:16 : Sending Get command and its XOR:
10:19:16 : byte 0x00 sent successfully to target
10:19:16 : byte 0xFF sent successfully to target
10:19:16 : Received response from target: 0x79
10:19:16 : Received response from target: 0x0b
10:19:16 : size of bytes in the response: 11
10:19:16 : Received response from target: 0x31000102112131446373829279
10:19:16 : Full received response: 0b31000102112131446373829279
10:19:16 : byte 0x11 sent successfully to target
10:19:16 : byte 0xEE sent successfully to target
10:19:16 : data sent successfully to target: 0x08000000
10:19:16 : byte 0x08 sent successfully to target
10:19:16 : byte 0x00 sent successfully to target
10:19:16 : byte 0xFF sent successfully to target
10:19:16 : Sending GetID command and its XOR:
10:19:16 : byte 0x02 sent successfully to target
10:19:16 : byte 0xFD sent successfully to target
10:19:16 : Received response from target: 0x79
10:19:16 : Received response from target: 0x01042979
10:19:16 : byte 0x11 sent successfully to target
10:19:16 : byte 0xEE sent successfully to target
10:19:16 : data sent successfully to target: 0x08000000
10:19:16 : byte 0x08 sent successfully to target
10:19:16 : byte 0x00 sent successfully to target
10:19:16 : byte 0xFF sent successfully to target
10:19:16 : Sending Read command and its XOR:
10:19:16 : byte 0x11 sent successfully to target
10:19:16 : byte 0xEE sent successfully to target
10:19:16 : Received response from target: 0x79
10:19:16 : Sending Read address and its checksum:
10:19:16 : data sent successfully to target: 0x40023c1c
10:19:16 : byte 0x62 sent successfully to target
10:19:16 : Received response from target: 0x79
10:19:16 : Sending number of bytes to be read - 1 and its checksum:
10:19:16 : data sent successfully to target: 0x03
10:19:16 : byte 0xFC sent successfully to target
10:19:16 : Received response from target: 0x1f
10:19:16 : Error: Number of bytes to be be read at address: 0x40023C1C not acknowledged!
10:19:16 : Sending Read command and its XOR:
10:19:16 : byte 0x11 sent successfully to target
10:19:16 : byte 0xEE sent successfully to target
10:19:16 : Received response from target: 0x1f
10:19:16 : Error: READ command not acknowledged at address: 0x40023C1C
10:19:16 : byte 0x11 sent successfully to target
10:19:16 : byte 0xEE sent successfully to target
10:19:16 : data sent successfully to target: 0x08000000
10:19:16 : byte 0x08 sent successfully to target
10:19:18 : Disabling memory Read Protection...
10:19:18 : Sending read unprotect command and its XOR:
10:19:18 : byte 0x92 sent successfully to target
10:19:18 : byte 0x6D sent successfully to target
10:19:18 : Received response from target: 0x1f
10:19:18 : Error: Disabling memory Read Protection failed
10:19:25 : Error: Connection to target must be established before performing the erase command.
10:19:32 : Error: Connection to target must be established before performing the erase command.
10:19:41 : Error: Connection to target must be established before performing the erase command.
10:19:44 : Serial Port cu.SLAB_USBtoUART is successfully opened.
10:19:44 : Sending init command: 
10:19:44 : byte 0x7F sent successfully to target
10:19:44 : Received response from target: 0x79
10:19:44 : Activating device: OK
10:19:44 : Sending GetID command and its XOR:
10:19:44 : byte 0x02 sent successfully to target
10:19:44 : byte 0xFD sent successfully to target
10:19:44 : Received response from target: 0x79
10:19:44 : Received response from target: 0x01042979
10:19:44 : Chip ID: 0x429 
10:19:44 : Sending Get command and its XOR:
10:19:44 : byte 0x00 sent successfully to target
10:19:44 : byte 0xFF sent successfully to target
10:19:44 : Received response from target: 0x79
10:19:44 : Received response from target: 0x0b
10:19:44 : size of bytes in the response: 11
10:19:44 : Received response from target: 0x31000102112131446373829279
10:19:44 : Full received response: 0b31000102112131446373829279
10:19:44 : byte 0x11 sent successfully to target
10:19:44 : byte 0xEE sent successfully to target
10:19:44 : data sent successfully to target: 0x08000000
10:19:44 : byte 0x08 sent successfully to target
10:19:44 : byte 0x00 sent successfully to target
10:19:44 : byte 0xFF sent successfully to target
10:19:44 : Sending GetID command and its XOR:
10:19:44 : byte 0x02 sent successfully to target
10:19:44 : byte 0xFD sent successfully to target
10:19:44 : Received response from target: 0x79
10:19:44 : Received response from target: 0x01042979
10:19:44 : byte 0x11 sent successfully to target
10:19:44 : byte 0xEE sent successfully to target
10:19:44 : data sent successfully to target: 0x08000000
10:19:44 : byte 0x08 sent successfully to target
10:19:44 : byte 0x00 sent successfully to target
10:19:44 : byte 0xFF sent successfully to target
10:19:44 : Sending Read command and its XOR:
10:19:44 : byte 0x11 sent successfully to target
10:19:44 : byte 0xEE sent successfully to target
10:19:44 : Received response from target: 0x79
10:19:44 : Sending Read address and its checksum:
10:19:44 : data sent successfully to target: 0x40023c1c
10:19:44 : byte 0x62 sent successfully to target
10:19:44 : Received response from target: 0x79
10:19:44 : Sending number of bytes to be read - 1 and its checksum:
10:19:44 : data sent successfully to target: 0x03
10:19:44 : byte 0xFC sent successfully to target
10:19:44 : Received response from target: 0x1f
10:19:44 : Error: Number of bytes to be be read at address: 0x40023C1C not acknowledged!
10:19:44 : Sending Read command and its XOR:
10:19:44 : byte 0x11 sent successfully to target
10:19:44 : byte 0xEE sent successfully to target
10:19:44 : Received response from target: 0x1f
10:19:44 : Error: READ command not acknowledged at address: 0x40023C1C
10:19:44 : byte 0x11 sent successfully to target
10:19:44 : byte 0xEE sent successfully to target
10:19:44 : data sent successfully to target: 0x08000000
10:19:44 : byte 0x08 sent successfully to target
10:19:54 : Disabling memory Read Protection...
10:19:54 : Sending read unprotect command and its XOR:
10:19:54 : byte 0x92 sent successfully to target
10:19:54 : byte 0x6D sent successfully to target
10:19:54 : Received response from target: 0x1f
10:19:54 : Error: Disabling memory Read Protection failed
10:19:56 : Serial Port cu.SLAB_USBtoUART is successfully opened.
10:19:56 : Sending init command: 
10:19:56 : byte 0x7F sent successfully to target
10:19:56 : Received response from target: 0x1f
10:19:56 : Error: Activating device: KO. Please, verify the boot mode configuration and check the serial port configuration. Reset your device then try again... 
10:20:02 : Serial Port cu.SLAB_USBtoUART is successfully opened.
10:20:02 : Sending init command: 
10:20:02 : byte 0x7F sent successfully to target
10:20:02 : Received response from target: 0x79
10:20:02 : Activating device: OK
10:20:02 : Sending GetID command and its XOR:
10:20:02 : byte 0x02 sent successfully to target
10:20:02 : byte 0xFD sent successfully to target
10:20:02 : Received response from target: 0x79
10:20:02 : Received response from target: 0x01042979
10:20:02 : Chip ID: 0x429 
10:20:02 : Sending Get command and its XOR:
10:20:02 : byte 0x00 sent successfully to target
10:20:02 : byte 0xFF sent successfully to target
10:20:02 : Received response from target: 0x79
10:20:02 : Received response from target: 0x0b
10:20:02 : size of bytes in the response: 11
10:20:02 : Received response from target: 0x31000102112131446373829279
10:20:02 : Full received response: 0b31000102112131446373829279
10:20:02 : byte 0x11 sent successfully to target
10:20:02 : byte 0xEE sent successfully to target
10:20:02 : data sent successfully to target: 0x08000000
10:20:02 : byte 0x08 sent successfully to target
10:20:02 : byte 0x00 sent successfully to target
10:20:02 : byte 0xFF sent successfully to target
10:20:02 : Sending GetID command and its XOR:
10:20:02 : byte 0x02 sent successfully to target
10:20:02 : byte 0xFD sent successfully to target
10:20:02 : Received response from target: 0x79
10:20:02 : Received response from target: 0x01042979
10:20:02 : byte 0x11 sent successfully to target
10:20:02 : byte 0xEE sent successfully to target
10:20:02 : data sent successfully to target: 0x08000000
10:20:02 : byte 0x08 sent successfully to target
10:20:02 : byte 0x00 sent successfully to target
10:20:02 : byte 0xFF sent successfully to target
10:20:02 : Sending Read command and its XOR:
10:20:02 : byte 0x11 sent successfully to target
10:20:02 : byte 0xEE sent successfully to target
10:20:02 : Received response from target: 0x79
10:20:02 : Sending Read address and its checksum:
10:20:02 : data sent successfully to target: 0x40023c1c
10:20:02 : byte 0x62 sent successfully to target
10:20:02 : Received response from target: 0x79
10:20:02 : Sending number of bytes to be read - 1 and its checksum:
10:20:02 : data sent successfully to target: 0x03
10:20:02 : byte 0xFC sent successfully to target
10:20:02 : Received response from target: 0x1f
10:20:02 : Error: Number of bytes to be be read at address: 0x40023C1C not acknowledged!
10:20:02 : Sending Read command and its XOR:
10:20:02 : byte 0x11 sent successfully to target
10:20:02 : byte 0xEE sent successfully to target
10:20:02 : Received response from target: 0x1f
10:20:02 : Error: READ command not acknowledged at address: 0x40023C1C
10:20:02 : byte 0x11 sent successfully to target
10:20:02 : byte 0xEE sent successfully to target
10:20:02 : data sent successfully to target: 0x08000000
10:20:02 : byte 0x08 sent successfully to target
10:21:24 : Error: Connection to target must be established before performing the read command.
```

**Comment by fpistm** [comment]
Did you set the Boot0 to 1 ?

**Comment by fpistm** [comment]
Hi @sabas1080,
there is a new version of STM32CubeProgrammer, could you try with it.
Anyway, I think I will rebuilt the stm32flasher with the fix.

**Comment by fpistm** [comment]
Small update, I will update soon all the current upload tools (STM32Flasher, STLink for windows and texane stlink for Linux/MacOS) to their latest version.
At this time, I could not integrate the STM32CubeProgrammer due to some issues (JRE,...)

**Comment by fpistm** [comment]
Hi @sabas1080 
Tools have been updated, so Serial upload will be ok for this target using the next release
See https://github.com/stm32duino/Arduino_Tools/pull/27

I think I will merge this PR as the basic support should be ok.
Are you ok @sabas1080 ?

**Pull request merged**
