### PR TITLE
Improve supported boards list

### PR DESCRIPTION
**Pull request by ThomasGravekamp**
**Summary**

Add links to new STM32-base board pages.
Add links to manufacturers websites under the "More info" links.
Add device(s) column.

I took the liberty to do a bit of reformatting of the supported boards list. I've added the device(s) column so that you can search for specific devices.

There's one open question though. There was this line:

```
| :green_heart: | [Black F407VET6](https://stm32-base.org/boards/STM32F407VET6-STM32-F4VE-V2.0) | *1.4.0* | VG/ZE/ZG in *1.5.0* |
```

The ZE/ZG variant of this board must be a completely different board, as those chips have got more pins. This may need to be split into two separate rows to prevent confusion about this one.

### CODE REVIEW

**Comment by fpistm** [comment]
> ```
> | :green_heart: | [Black F407VET6](https://stm32-base.org/boards/STM32F407VET6-STM32-F4VE-V2.0) | *1.4.0* | VG/ZE/ZG in *1.5.0* |
> ```
> 
> 
> The ZE/ZG variant of this board must be a completely different board, as those chips have got more pins. This may need to be split into two separate rows to prevent confusion about this one.

Right and it is managed. I guess it was left on the same line because they are all managed in the same variant folder:
Vx:
https://github.com/stm32duino/Arduino_Core_STM32/blob/1eac7c56ab65bd73b79d4237c00121a767cbcb24/variants/BLACK_F407XX/variant.h#L121
Zx:
https://github.com/stm32duino/Arduino_Core_STM32/blob/1eac7c56ab65bd73b79d4237c00121a767cbcb24/variants/BLACK_F407XX/variant.h#L251

The improvement seems nice for me, the main issue I can see is the link to the Board available which has been removed and it is used in several Wiki, docs,...
So I wonder if it will be possible to keep it for backward compatibility.

**Comment by ThomasGravekamp** [comment]
Right, I'll add a new row to the table for the Zx variants of that particular board.

> The main issue I can see is the link to the Board available which has been removed and it is used in several Wiki, docs,...

I can't think of a way to keep the old anchor intact. The wiki can be updated easily by globally replacing the old link with the new link.

Which other docs rely on that anchor? Are these docs that are under control of stm32duino or do you mean external docs like websites linking to that anchor?

If you feel like changing the anchor breaks too many things, we can leave those changes out.

**Comment by fpistm** [comment]
I guess it can be break, I will update in the wiki and in all other place I think (remember) 😉
For example here:
https://github.com/arduino/Arduino/wiki/Unofficial-list-of-3rd-party-boards-support-urls

**Comment by ThomasGravekamp** [comment]
Force pushed a new commit with a new row for the Black STM32F407Zx board.

**Comment by ThomasGravekamp** [comment]
Just added two new board pages to STM32-base. Added a link for the FK407M1 board to the list.

**Pull request merged**
