### PR TITLE
Astyle deployement

### PR DESCRIPTION
**Pull request by fpistm**
AStyle will be used for coding style checking.
Only sources files (`*.h`, `*.hpp`, `*.c`, `*.cpp`) from the following lists will be check:
* cores
* libraries
* variants

`.astyleignore` file contains list of folder to ignore.

Hereafter the code style definition applied (`.astylerc`):

```bash
# STM32duino code style definition file for astyle

# Don't create backup files, let git handle it
suffix=none

# K&R style
style=kr

# 1 TBS addition to k&r, add braces to one liners
# Use -j as it was changed in astyle from brackets to braces, this way it is compatible with older astyle versions
-j

# 2 spaces, convert tabs to spaces
indent=spaces=2
convert-tabs

# Indent switches and cases
indent-classes
indent-switches
indent-cases
indent-col1-comments

# Remove spaces in and around parentheses
unpad-paren

# Insert a space after if, while, for, and around operators
pad-header
pad-oper

# Pointer/reference operators go next to the name (on the right)
align-pointer=name
align-reference=name

# Attach { for classes and namespaces
attach-namespaces
attach-classes

# Extend longer lines, define maximum 120 value. This results in aligned code,
# otherwise the lines are broken and not consistent 
max-continuation-indent=120

# if you like one-liners, keep them
keep-one-line-statements
```

Python script `astyle.py` is provided to ease use of AStyle:

```stdout
usage: astyle.py [-h] [-d <code style definition file>]
                 [-g | -b <branch name>] [-i <ignore file>]
                 [-p <astyle install path>] [-r <source root path>]

Launch astyle on source files found at specified root path.

optional arguments:
  -h, --help            show this help message and exit
  -d <code style definition file>, --definition <code style definition file>
                        Code style definition file for Astyle. Default: <repo path>/Arduino_Core_S
                        TM32/CI/astyle/.astylerc
  -g, --gitdiff         Use changes files from git default branch. Default:
                        remotes/origin/master
  -b <branch name>, --branch <branch name>
                        Use changes files from git specified branch.
  -i <ignore file>, --ignore <ignore file>
                        File containing path to ignore. Default: <repo path>/Arduino_Core_STM32/CI
                        /astyle/.astyleignore
  -p <astyle install path>, --path <astyle install path>
                        Astyle installation path
  -r <source root path>, --root <source root path>
                        Source root path to use. Default: <repo path>/Arduino_Core_STM32
```

### CODE REVIEW

**Comment by BennehBoy** [comment]
@fpistm so, locally, we just run astyle.py against our local folder before commiting to see what needs fixing?

**Comment by fpistm** [comment]
yes.
I will add some guidance in the contributing.md when I will release this.
This PR will add AStyle check to Travis CI build then if new code doesn't follow the coding style then this will be failed.

**Comment by fpistm** [comment]
No, I mainly develop under Linux and use gvim. I do all using command lines 😄

**Comment by fpistm** [comment]
No, I mainly develop under Linux and use gvim. I do all using command lines 😄

**Comment by BennehBoy** [comment]
Hmm, gvim has come on quite a way I may give it a try.

**Comment by BennehBoy** [comment]
@fpistm need more docs on what the style items in the config above are, or means to convert existing code... as it stands I'm clueless what Astyle's error report is actually saying, the output from it does not match the code I submitted.

**Comment by fpistm** [comment]
The output is the code formatted. Simply apply astyle with the config provided then your code will be ok.

**Pull request merged**
