### PR TITLE
Changes for FreeRTOS Library.

### PR DESCRIPTION
**Pull request by straccio**
I have made, not yet published, the FreeRTOS Library for stm32.
In order to get the library working i need this changes (not platform.txt).

### CODE REVIEW

**Comment by straccio** [comment]
Here the FreeRTOS Library
https://github.com/straccio/stm32FreeRTOS-duino

**Comment by straccio** [comment]
Ops

**Comment by fpistm** [comment]
Thanks @straccio 
I will have a look to this soon.

**Comment by fpistm** [comment]
Seems you merge the master into your branch instead of rebase it. 
Your FreeRTOS library are only for F4?

**Comment by straccio** [comment]
I have only one board in order to test, the stm32f4.
Yesterday I have made some changes to the config that can made it compatible with other boards.
Today I'll push these changes to the library repo.

**Comment by fpistm** [comment]
Hi @straccio ,
I've created another PR #190 based on this one which included some unneeded merge.
Moreover, I've managed to provide also an Arduino FreeRTOS library for STM32.
You could have a look here:
https://github.com/stm32duino/STM32FreeRTOS/pull/1

**Comment by straccio** [comment]
Good morning,
i'm back from holiday. Today i give a look! Tnx!

**Comment by fpistm** [comment]
Hi @straccio 
Welcome back and happy new year ;)
Thanks in advance

**Comment by straccio** [comment]
Tnx, and happy new year! ^^

**Comment by fpistm** [comment]
#190 merged. Closed this one.

**Pull request closed without merging**
