### PR TITLE
Corrected NUCLEO_F429ZI f_cpu, added support for Multicast UDP (stm32Ethernet library)

### PR DESCRIPTION
**Pull request by straccio**
Sorry, i'm a noob... i can't understand how to pull only the changes after the merge upstream.

### CODE REVIEW

**Comment by fpistm** [comment]
Hi @straccio,
For F_CPU, in fact this not very important. The F_CPU is not really used. `SystemCoreClock `is well initialized during the `SystemClock_Config()`
About IGMP, is this changed the beahavior of LWIP Stack?

Finally about the merge of the upstream.
In fact, in your local repo you should have 2 remotes url ( one on the official repo and one on your fork).
Ex of my local repo:
> $ git remote -v
> fpistm  https://github.com/fpistm/Arduino_Core_STM32.git (fetch)
> fpistm  https://github.com/fpistm/Arduino_Core_STM32.git (push)
> stm32duino      https://github.com/stm32duino/Arduino_Core_STM32.git (fetch)
> stm32duino      https://github.com/stm32duino/Arduino_Core_STM32.git (push)

fpistm is alias on my fork, stm32duino the official repo.

Tips:
To add an alias `stm32duino ` of the official repo on your local repo:
> $ git remote add stm32duino https://github.com/stm32duino/Arduino_Core_STM32.git
To rename an alias (ex: `origin` to `straccio`):
> $ git remote rename origin straccio

So, you should have:
> $ git remote -v
> stm32duino      https://github.com/stm32duino/Arduino_Core_STM32.git (fetch)
> stm32duino      https://github.com/stm32duino/Arduino_Core_STM32.git (push)
> straccio https://github.com/straccio/Arduino_Core_STM32.git (fetch)
> straccio https://github.com/straccio/Arduino_Core_STM32.git (push)

Then to align official and fork: 
1- fetch the official git repo to have the latest commits:
> $ git fetch stm32duino

2- Reset the master branch to the head of stm32duino
> $ git checkout -B master stm32duino/master

3- push this master on your fork
> $ git push straccio master

Then you could rebase your dev branch on the master

**Comment by lacklustrlabs** [comment]
The changes in platform.txt, are they suppose to be in there?
I thought that is what you need to change to make this work with the git repository instead of board manager. https://github.com/stm32duino/wiki/wiki/Using-git-repository

BTW those platform.txt changes are better suited for platform.local.txt, I'll see if I can find time to modify the wiki later today.

**Comment by fpistm** [comment]
No the change in platform.txt should be ignore
It was for using the package installed thanks the board manager.

**Comment by fpistm** [comment]
With #207, this PR is no more required. Update should be done at library side

**Pull request closed without merging**
