### PR TITLE
Added Generic L0xx Boards

### PR DESCRIPTION
**Pull request by alextrical**
| :yellow_heart: | STM32L010C6 | Generic Board | **2.4.0** |  |
| :yellow_heart: | STM32L010F4 | Generic Board | **2.4.0** |  |
| :yellow_heart: | STM32L010R8 | Generic Board | **2.4.0** |  |
| :yellow_heart: | STM32L011D3<br>STM32L011D4 | Generic Board | **2.4.0** |  |
| :yellow_heart: | STM32L011E3<br>STM32L011E4 | Generic Board | **2.4.0** |  |
| :yellow_heart: | STM32L011F3<br>STM32L011F4 | Generic Board | **2.4.0** |  |
| :yellow_heart: | STM32L011G3<br>STM32L011G4 | Generic Board | **2.4.0** |  |
| :yellow_heart: | STM32L011K3<br>STM32L011K4 | Generic Board | **2.4.0** |  |
| :yellow_heart: | STM32L021F4 | Generic Board | **2.4.0** |  |
| :yellow_heart: | STM32L021D4 | Generic Board | **2.4.0** |  |
| :yellow_heart: | STM32L021F4 | Generic Board | **2.4.0** |  |
| :yellow_heart: | STM32L021G4 | Generic Board | **2.4.0** |  |
| :yellow_heart: | STM32L021K4 | Generic Board | **2.4.0** |  |
| :yellow_heart: | STM32L031C4<br>STM32L031C6 | Generic Board | **2.4.0** |  |
| :yellow_heart: | STM32L031E4<br>STM32L031E6 | Generic Board | **2.4.0** |  |
| :yellow_heart: | STM32L031F4<br>STM32L031F6 | Generic Board | **2.4.0** |  |
| :yellow_heart: | STM32L031G4<br>STM32L031G6 | Generic Board | **2.4.0** |  |
| :yellow_heart: | STM32L041C4<br>STM32L041C6 | Generic Board | **2.4.0** |  |
| :yellow_heart: | STM32L041E6 | Generic Board | **2.4.0** |  |
| :yellow_heart: | STM32L041F6 | Generic Board | **2.4.0** |  |
| :yellow_heart: | STM32L041G6 | Generic Board | **2.4.0** |  |
| :yellow_heart: | STM32L052C6<br>STM32L052C8 | Generic Board | **2.4.0** |  |
| :yellow_heart: | STM32L052K6<br>STM32L052K8 | Generic Board | **2.4.0** |  |
| :yellow_heart: | STM32L052R6<br>STM32L052R8 | Generic Board | **2.4.0** |  |
| :yellow_heart: | STM32L052T6<br>STM32L052T8 | Generic Board | **2.4.0** |  |
| :yellow_heart: | STM32L053C6<br>STM32L053C8 | Generic Board | **2.4.0** |  |
| :yellow_heart: | STM32L053R6<br>STM32L053R8 | Generic Board | **2.4.0** |  |
| :yellow_heart: | STM32L062C8 | Generic Board | **2.4.0** |  |
| :yellow_heart: | STM32L062K8 | Generic Board | **2.4.0** |  |
| :yellow_heart: | STM32L063C8 | Generic Board | **2.4.0** |  |
| :yellow_heart: | STM32L072CB<br>STM32L072CZ | Generic Board | **2.4.0** |  |
| :yellow_heart: | STM32L072KB<br>STM32L072KZ | Generic Board | **2.4.0** |  |
| :yellow_heart: | STM32L072RB<br>STM32L072RZ | Generic Board | **2.4.0** |  |
| :yellow_heart: | STM32L072V8<br>STM32L072VB<br>STM32L072VZ | Generic Board | **2.4.0** |
| :yellow_heart: | STM32L073V8<br>STM32L073VB<br>STM32L073VZ | Generic Board | **2.4.0** |
| :yellow_heart: | STM32L073CB<br>STM32L073CZ | Generic Board | **2.4.0** |  |
| :yellow_heart: | STM32L073RB<br>STM32L073RZ | Generic Board | **2.4.0** |  |
| :yellow_heart: | STM32L082CZ | Generic Board | **2.4.0** |  |
| :yellow_heart: | STM32L082KB<br>STM32L082KZ | Generic Board | **2.4.0** |  |
| :yellow_heart: | STM32L083CB<br>STM32L083CZ | Generic Board | **2.4.0** |  |
| :yellow_heart: | STM32L083RB<br>STM32L083RZ | Generic Board | **2.4.0** |  |
| :yellow_heart: | STM32L083V8<br>STM32L083VB<br>STM32L083VZ | Generic Board | **2.4.0** |

### CODE REVIEW

**Review by ABOSTM — APPROVED** [review]
LGTM

**Review by ABOSTM — CHANGES_REQUESTED** [review]
missing parenthesis in linker files

**Comment by alextrical** [comment]
> missing parenthesis in linker files
I wish I could tell you how that happened. I can only assume I managed to mangle the RegEx that processed those files. Attempting to fix them all now

**Comment by ABOSTM** [comment]
CI failed is linked to issue #1798, we will take care of it.

**Pull request merged**
