### PR TITLE
Generic Serial

### PR DESCRIPTION
**Pull request by fpistm**
This PR allows to have `Serial `mapped on `SerialUSB `if USB CDC is enabled.

If USB CDC is enabled then the generic "`Serial`" used will be `SerialUSB`
else this is the `HardwareSerial `if one is defined.
    
 If `Serial `is defined before (`build_opt.h`, `variant.h`)
then this is the one used.
    
 ISO for generic "`serialEvent`".

### CODE REVIEW

**Comment by BennehBoy** [comment]
Does this affect the naming sequence of the other Serial instances?

Ie will Serial3 become Serial 2 if Serial is remapped to USB?

**Comment by fpistm** [comment]
@BennehBoy, no
Default instance naming is:
 * `SerialX `== U(S)ARTX
 * `SerialUSB `== CDC

`Serial `name is a defined to have a generic way to access default _Serial_.

**Comment by fpistm** [comment]
I've updated/reword the menu to have better description and usage.
Let me know what you think.

**Comment by BennehBoy** [comment]
Looks good

**Pull request merged**
