### PR TITLE
F103Zx support

### PR DESCRIPTION
**Pull request by fpistm**
Add Generic F103Zx support and VCCGND_F103ZET6 (Mini)

I have not this boards so if someone could do some tests that's would be fine.
Thanks.

### CODE REVIEW

**Comment by fpistm** [comment]
@dds90 could you test this please?

**Comment by dds90** [comment]
Hi  @fpistm,
thanks for your contribute.

At the moment I've tested some peripherials in VCCGND_F103ZET6 (Mini):
- SD seems work correctly
- The Analog pins connected to ADC2 and ADC3 lock the Serial
- Second and Third serial not work yet.

**Comment by fpistm** [comment]
How did you test the, other serial ?

**Comment by dds90** [comment]
Like this:
```
void setup() {
Serial.begin(19200);   // on PA9 PA10
Serial2.begin(19200);  // on PA3 PA2
Serial3.begin(19200);  // on PB11 PB10

Serial.println("Serial");
Serial2.println("Serial2");
Serial3.println("Serial3!");
}

void loop() {
}
```

**Comment by fpistm** [comment]
That's what I thought.
By default only one Serial instance is instantiate.
In this case Serial1 using USART1 on PA10/PA9.

To use other Serial you have to instantiate them:
```
HardwareSerial Serial2(PA3, PA2);
HardwareSerial Serial3(PB11, PB10);
```

**Comment by dds90** [comment]
Thanks again.
With your code and only Serial and Serial2 work well.
But when I add the Serial3 instance , it send only one character, and Serial and Serial2 send only two characters.

**Comment by fpistm** [comment]
@dds90 
I've tested with a VCC GND F103ZE and all Serials works.

**Comment by dds90** [comment]
@fpistm
Please can you share your testing code?
Did you tested the the analog pins also?

**Comment by fpistm** [comment]
This is the same than the one you provided adding the fix I gave you. ADC is working except ADC3 which is a know issue

**Comment by fpistm** [comment]
```c++
HardwareSerial Serial2(PA3, PA2);
HardwareSerial Serial3(PB11, PB10);

void setup() {
  Serial.begin(19200);   // on PA9 PA10
  Serial2.begin(19200);  // on PA3 PA2
  Serial3.begin(19200);  // on PB11 PB10

  Serial.println("Serial");
  Serial2.println("Serial2");
  Serial3.println("Serial3!");
}

void loop() {
}
```

**Comment by dds90** [comment]
Many thanks!
For the serials i retry as soon as possible. For the ADC are there any chances to fix this issue?

**Comment by fpistm** [comment]
> For the serials i retry as soon as possible. For the ADC are there any chances to fix this issue?

Only ADC3 is not working ADC1 and 2 works fine anyway, I have currently no clue. As a workaround I will comment all ADC3 in the PeripheralPins.c

**Comment by dds90** [comment]
I confirm that all serials are ok.
In the previously test, i wrong to add the instances in to the setup function.

The pins from PF_6 to PF_10 can't remap to another ADC. Where did you read the ADC3 issue?

**Comment by fpistm** [comment]
On the forum one member told that ADC3 doesn't work.Then I confirm, there is the same issue with Rogers's core.

**Comment by dds90** [comment]
Is there the possibility that it is a bug in the STM32F1 series?

**Comment by fpistm** [comment]
@dds90 
> Is there the possibility that it is a bug in the STM32F1 series?

Well, currently I don't know. All is possible anyway, the STM32F1 serie is old then I guess this kind of issue would be report in the errata sheet. So, we will investigate.

**Comment by dds90** [comment]
@fpistm
Do you think it is necessary to open a new issue?

**Comment by fpistm** [comment]
Issue is fixed.

**Comment by dds90** [comment]
Oh, sorry.
Thank you very much!

**Pull request merged**
