### PR TITLE
make cmake work on macos

### PR DESCRIPTION
**Pull request by nathantsoi**
**Summary**

cmake's downloads (ctags and toolchain) were not working on macos.

**Validation**

tested on mac os 13.4.1 and cmake 3.26.4

### CODE REVIEW

**Comment by nathantsoi** [comment]
One caveat here. I found that the [ctags for macOS on the Arduino github releases page](https://github.com/arduino/ctags/releases/tag/5.8-arduino11) is not 64-bit, however, the distributed ctags is... so I also had to:

```
cp /Applications/Arduino.app/Contents/Java/tools-builder/ctags/5.8-arduino11/ctags ~/.Arduino_Core_STM32_dl/d726370579d207be3e43211ba220e5b1/dist/ctags
```

I'm not sure if a 64-bit ctags binary is available outside of the Arduino installer, but this would be a better solution.

**Comment by fpistm** [comment]
As an extra information: which Mac-OS version you used ?

**Comment by nathantsoi** [comment]
MacOS version is Ventura `13.4.1`

And yes, @massonal, the [x86_64 zip](https://github.com/arduino/ctags/releases/download/5.8-arduino11/ctags-5.8-arduino11-x86_64-apple-darwin.zip) contains an i386 executable: 

```
$ wget https://github.com/arduino/ctags/releases/download/5.8-arduino11/ctags-5.8-arduino11-x86_64-apple-darwin.zip
$ unzip ctags-5.8-arduino11-x86_64-apple-darwin
Archive:  ctags-5.8-arduino11-x86_64-apple-darwin.zip
  inflating: ctags
$ file ctags
ctags: Mach-O executable i386
```

vs. The correct, 64-bit version included with the arduino app:

```
$ file /Applications/Arduino.app/Contents/Java/tools-builder/ctags/5.8-arduino11/ctags
/Applications/Arduino.app/Contents/Java/tools-builder/ctags/5.8-arduino11/ctags: Mach-O 64-bit executable x86_64
```

**Comment by fpistm** [comment]
@nathantsoi you don't answer this question from  @massonal 

> Did you really observe the value "macOS"?! (That's fine, but it would mean the docs are confusing...)

On our side a MacBook Pro with Monterey v12.6.1  is used to validate and result of `uname -s` is `Darwin`.
It seems strange the result was changed and CMAKE documentation was not updated.
Looking on Ventura, it is always based on Darwin kernel.  Ventura version 13.4.1 is based on 22.5.0 Darwin kernel.

**Comment by nathantsoi** [comment]
Correct, I get the string `macOS`:

(Snippet from `FindArduinoCtags.cmake`)
```
cmake_host_system_information(
  RESULT HOSTINFO
  QUERY OS_NAME OS_PLATFORM
)
list(GET HOSTINFO 0 HOST_OS)
list(GET HOSTINFO 1 HOST_ARCH)
message(HOST_OS=${HOST_OS})
```

Results in:
```
HOST_OS=macOS
```

**Comment by massonal** [comment]
Thanks for the confirmation @nathantsoi.
Then, it seems like it's a bug on CMake side (they probably forgot to update the doc at some point? 🤷 )
I suggest you raise a ticket by them... https://github.com/Kitware/CMake#reporting-bugs

As for the issue you have with ctags, do you see any functional impact from the 32-bits version?
I think here we'll try to stick to official releases as much as possible...
You can nonetheless raise an issue there too to ask for clarification! https://github.com/arduino/ctags

My final take on this PR: it does not introduce any *bug*, so it may be merged safely.
I'll let @fpistm decide on whether to merge it or wait on upstream fixes in the tools.

**Review by massonal — COMMENTED** [review]
This code is bug-less and harm-less.
Merging it is a matter of policy.

**Comment by nathantsoi** [comment]
Re. the macOS string, I'll open a ticket w/ cmake.

Re. ctags, I should clarify that the 32-bit version of ctags will not run on macOS 13.x.

Using the https://github.com/arduino/ctags binary results in this error:

```
/bin/sh: /Users/ntsoi/.Arduino_Core_STM32_dl/d726370579d207be3e43211ba220e5b1/dist/ctags/ctags: Bad CPU type in executable
```

Hence the need to copy in the 64-bit version from the Arduino.app

Perhaps this can be noted in the cmake setup documentation for now? I am happy to do this if you would like.

**Comment by nathantsoi** [comment]
Actually, @massonal, I just checked
```
message(CMAKE_HOST_SYSTEM_NAME=${CMAKE_HOST_SYSTEM_NAME})
```

And this does yield the documented result: `CMAKE_HOST_SYSTEM_NAME=Darwin`

Note, this is different from the snippets in `ensure_core_deps.cmake` and `FindArduinoCtags.cmake` (https://github.com/stm32duino/Arduino_Core_STM32/pull/2060#issuecomment-1629128352)

**Comment by massonal** [comment]
That last item with `CMAKE_HOST_SYSTEM_NAME` really is confusing... `cmake_host_system_information` does redirect to it.

> OS_NAME
> New in version 3.10.

> 
> See [CMAKE_HOST_SYSTEM_NAME](https://cmake.org/cmake/help/latest/variable/CMAKE_HOST_SYSTEM_NAME.html#variable:CMAKE_HOST_SYSTEM_NAME)

Definitely mention that in the ticket you write to CMake!

**Comment by fpistm** [comment]
> Perhaps this can be noted in the cmake setup documentation for now? I am happy to do this if you would like.

Feel free to submit a PR for that 😉

**Pull request merged**
