### PR TITLE
fix: variant default i2c pointed to i2c2

### PR DESCRIPTION
**Pull request by afewyards**
## Pull Request template

Please, Make sure that your PR is not a duplicate.
Search among the [Pull request](https://github.com/stm32duino/Arduino_Core_STM32/pulls) before creating one.

IMPORTANT: Please review the [CONTRIBUTING.md](../CONTRIBUTING.md) file for detailed contributing guidelines.

Thanks for submitting a pull request.
Please provide enough information so that others can review your pull request:

**Summary**

The default (channel 1) i2c pins for these chips is SCL: pb6 and SDA pb7.

This PR fixes/implements the following **bugs/features**

* [x] Fixes default i2c pins for these chip
* [ ] Bug 2
* [ ] Feature 1
* [ ] Feature 2
* [ ] Breaking changes

Explain the **motivation** for making this change. What existing problem does the pull request solve?

**Validation**

* Ensure CI build is passed.
* Demonstrate the code is solid. [e.g. Provide a sketch]

**Code formatting**

* Ensure AStyle check is passed thanks CI

**Closing issues**

Fixes #xxx

### CODE REVIEW

**Comment by fpistm** [comment]
Hi @afewyards 
By default it point to I2C1 on PB9/PB8 not on I2C2.
https://github.com/stm32duino/Arduino_Core_STM32/blob/1faf0a0ead7b6ae07258d706c1e9052de0be6cf0/variants/Generic_F4x3Cx/PeripheralPins.c#L60
https://github.com/stm32duino/Arduino_Core_STM32/blob/1faf0a0ead7b6ae07258d706c1e9052de0be6cf0/variants/Generic_F4x3Cx/PeripheralPins.c#L71

It is a default choice which can be overridden using `Wire.setSDA()`  and `Wire.setSCL()` before the call of `Wire.begin()`.

**Comment by afewyards** [comment]
Hmmm, now that I look more closely at the datasheet it does say that i2c1 is supported on a range. Just that for the STM32 ide it preselects the B6 and B7. Also, the other chip I've used in the F4 range (https://github.com/stm32duino/Arduino_Core_STM32/blob/master/variants/Generic_F411Cx/variant.h) with stm32duino have the B6 and B7 selected as default.

And looking at the other chips in the range they default to what you stated so this look correct. Ii guess the inconsistency is in that file

**Comment by fpistm** [comment]
Default I2C pins for Wire is a choice and not related to the mcu.
There is no issue to have  2 pins on one board and 2 other on an other one eve if it is the same MCU.
You want to change to PB6 and PB7 but an other user could prefer PB8 PB9.

When you said:

> The default (channel 1) i2c pins for these chips is SCL: pb6 and SDA pb7.

It is not correct. Every I2C pins can be used as a default. That's why you can simply change them in the code.
If you create a new board you can also create your own variant using your own configuration. The variant is simply a way to define a board pin mapping.

**Comment by afewyards** [comment]
thanks for the explanation

**Pull request closed without merging**
