### PR TITLE
Add generic F103Cx targets

### PR DESCRIPTION
**Pull request by MCUdude**
This adds generic F103C4, F103C6, F103C8 and F103CB targets.

### CODE REVIEW

**Comment by MCUdude** [comment]
@fpistm For some strange reason, the CI fails when trying to compile BareMinimum for F103C4 (not enough space). However, it compiles just fine in my Arduino IDE install.

**Comment by fpistm** [comment]
> mpile BareMinimum for F103C4 (not enough space). However, it compiles just fine in my Arduino IDE install.

The sketch BareMinimum of the CI use several API  to test the build that's why it does not fit in the FLASH, anyway it should be considered as succeeded  with a '*'.
I will fix that.

**Comment by fpistm** [comment]
@MCUdude 
I've fix the issue with the CI: https://github.com/stm32duino/Arduino_Core_STM32/commit/6eaa8d20d69782ac346f6bc7d094cf078aba6d2c

If you rebase your PR on top of the master this would be ok.

**Comment by MCUdude** [comment]
Thanks, it should be OK now. I forgot to add the new targets to README, so I did another rebase and got everything into one commit, which I know you prefer 😉

**Comment by MCUdude** [comment]
> I will review all system clock config to unified them and handle HSE, HSE bypass, and HSI

Great! That should be the same for all F103 targets I believe. I also have an F103Vx pinout ready I may be able to publish a PR this evening. IIRC this variant has been requested earlier.

**Pull request merged**
