### PR TITLE
Add DIYMROE_STM32F407VGT support

### PR DESCRIPTION
**Pull request by fpistm**
PR linked to #374 thanks @AndySymons 
Reviewed by @fpistm 
* Clean up file format, trailing space and code format
* Fix some typo
* Define default SPI pins and I2C used for SPI and Wire instances.
* Fix analog pins definition

### CODE REVIEW

**Comment by AndySymons** [comment]
How do I download the modified core to test it?

**Comment by fpistm** [comment]
Best way would be to use git.
Anyway, here the zip of modified file.
Note that boards.txt is the last version (on top of the master branch)  and differs from yours (which I guess is the 1.4.0 version)
[PR376-DIYMROE.zip](https://github.com/stm32duino/Arduino_Core_STM32/files/2600883/PR376-DIYMROE.zip)

**Comment by AndySymons** [comment]
Yes, I’d like to use git, but don’t know how. 
Yes, I used the 1.4.0 version, downloaded using the Arduino Boards Manager. 
I guess at some point the update will appear in the next Boards Manager version? 

In the meantime I can test it by manually reintegrating it, but I am going to be away for the next week or so, so it will take while. 

Thanks for your help with this. 

Andy

**Comment by fpistm** [comment]
To use the git repo with the core:
https://github.com/stm32duino/wiki/wiki/Using-git-repository

Then to pull the PR, add in your .gitconfig:
```
[Alias]
        pr = "!f() { git fetch -fu ${2-origin} refs/pull/$1/head:pr/$1 && git checkout pr/$1; }; f"
```
then you can do:
`git pr 376`
This will pull the PR in your git repo in a branch PR/376.

**Comment by AndySymons** [comment]
Thanks! 
A

**Comment by fpistm** [comment]
Hi @AndySymons 
Did you made some tests?
Is it ok to merge?

**Comment by AndySymons** [comment]
Frederic,
I tested my own version as far as making a blink test. I do not know how to test your version as I am not familiar enough with Github to get hold of it. 
Andy

**Comment by BennehBoy** [comment]
I tested this today, I can get a simple blink sketch to work just fine.

I also tested using something more complex, SPI1 & Usarts are functional.

Main comment is the naming, the manufacturer is called DIYMORE & not DIYMROE

**Comment by fpistm** [comment]
@BennehBoy 
About the name it seems not to be a mistake. @AndySymons comment on that on the forum.
See picture here http://www.stm32duino.com/viewtopic.php?f=2&t=4153&p=49844#p49806 
But if this is a clone maybe we can rename it to DIYMORE to support the "official" one and user having a clone can use it as well.

About USB, the `PinNamesVar.h` and `PeripheralPins.c` do not contains USB info. I will update the PR.

**Comment by fpistm** [comment]
@AndySymons let me know what you think about the renaming?
If this is the same pin mapping then I guess it could be the best choice

**Comment by BennehBoy** [comment]
PS, I just tried the device with Roger's core and CDC works although exhibits the same bug with the device params from PR #388.  I know this is OT for this PR, just for info.

**Comment by fpistm** [comment]
Thanks @BennehBoy 
About name I think it should be better to keep it as I'm not able to find an official DIYMORE board.
Even if the brand name is DIYMORE on some sellers all picture show DIYMROE.
https://www.amazon.com/Diymore-STM32F407VGT6-Cortex-M4-Discovery-Development/dp/B01M7YB5HF

**Comment by BennehBoy** [comment]
Yes it's a bit strange, even in the link you posted the board has diymroe on the upper side, and diymore on the lower 🤣

**Comment by fpistm** [comment]
Right, ;) did not see that before. anyway this is only a name but I would not use a brand name if this is not the right one. And for this it seems this is not the right one as not referenced on official DIYMORE site.

**Comment by BennehBoy** [comment]
👍

**Comment by fpistm** [comment]
Ok then I will rebase it and update PinNamesVar.h and PeripheralPins.c to add USB info then merge it.

**Comment by BennehBoy** [comment]
> Ok then I will rebase it and update PinNamesVar.h and PeripheralPins.c to add USB info then merge it.

Hmm, I did try this already and it did not work.... Hopefully your attempt will be more successful.

**Comment by BennehBoy** [comment]
I noticed that you replaced the '0' with 'GPIO_AF_NONE'
```
	Line 362:   {PA_9,  USB_OTG_FS, STM_PIN_DATA(STM_MODE_INPUT, GPIO_NOPULL, GPIO_AF_NONE)}, // USB_OTG_FS_VBUS
	Line 388:   {PB_13, USB_OTG_HS, STM_PIN_DATA(STM_MODE_INPUT, GPIO_NOPULL, GPIO_AF_NONE)}, // USB_OTG_HS_VBUS
```

This fails to compile on my system:
```
error: 'GPIO_AF_NONE' undeclared here (not in a function)

   {PA_9,  USB_OTG_FS, STM_PIN_DATA(STM_MODE_INPUT, GPIO_NOPULL, GPIO_AF_NONE)}, // USB_OTG_FS_VBUS

```
Where is this defined?

**Comment by BennehBoy** [comment]
I've retested USB CDC FS multiple times now, reconstructing my core each time from a fresh master clone, + pr 388, + manual merge in of the DIYMROE last commit (your force push) + the Bdevice changes.

With or without the TIM changes for 388 I do not get a working USB device (unrecognized)

Using the exact same hardware I get a working USB Serial device using either STM32GENERIC, or Roger's core.  

I've tested this on both Windows 10 & Ubuntu 18.04.1 LTS

However, pinpointing the issue is beyond my knowledge/skill level.

**Comment by fpistm** [comment]
I will update with all input next week and do several tests on my side. I've got an USB shield to test across al series.

**Comment by BennehBoy** [comment]
@AndySymons yeah with hindsight I think the naming makes sense - I searched diymore.cc and they don't offer this product.

@fpistm, looking instm32f4xx_hal_conf.h I can see some differences compared to the black407VE:

there is no typing of most of the defines..

eg BLACK407VET:
#define  VDD_VALUE		      ((uint32_t)3300U

and DIYMROE:
#define  VDD_VALUE                    3300U

The only other difference (other than where items appear in order), is TICK_INT_PRIORITY,

For BLACK407VET it is: ((uint32_t)0U) 

and DIYMROE: 0x0FU

Although this matches the DISCO407VG config.

**Comment by BennehBoy** [comment]
OK, I've resolved this....

In Variants.cpp

`  RCC_OscInitStruct.PLL.PLLM = 25;`

Needs to be

`  RCC_OscInitStruct.PLL.PLLM = 8;`

**Comment by fpistm** [comment]
Right, this is what I though. In fact HSE oscillator is a 8MHz right ? while I thought it was a 25 MHz.

**Comment by BennehBoy** [comment]
> Right, this is what I though. In fact HSE oscillator is a 8MHz right ? while I thought it was a 25 MHz.

Yes it's 8mhz.  I added a PR for this to your DIYMROE branch.

**Comment by fpistm** [comment]
I saw it and merge it, so it is now part of this PR. You will be a new contributor ;)
I guess this PR is ready to merge. From my point of view it is OK, even if I could not test it as I do not have the board.

**Comment by BennehBoy** [comment]
One other small change, this board has 1024KB flash, boards.txt configures only 512KB.

**Comment by fpistm** [comment]
Right PR updated with 1024Kb

**Pull request merged**
