### PR TITLE
I2C slave: allow function wrapped callbacks

### LINKED ISSUE #1833: Wire add support for callback_function_t callbacks
**Is your feature request/improvement related to a problem? Please describe.**

The Wire methods onReceive and onRequest dont allow to pass a function via std::bind.
This would result to have to use a singleton to have access the hanlders if the I2C client code is an object like a library.

A solution similar to the attachInterrupt would solve the issue.

**Describe the solution you'd like**
Something like this (similar to what we do with `attachInterrupt()`)

```cpp
   _i2bus->begin(address + baseAddress);
   _i2bus->onReceive(std::bind(&I2CClient::onReceive, this));
   _i2bus->onRequest(std::bind(&I2CClient::onRequest, this));
```
My current workaround is to have multiple definitions of the static handling methods
each pair call the right object handling methods.

This is not the best solution with `callback_function_t` I could just pass the Wire object to class instanceand it will self manage.

Another solution would be to pass the object pointer to the registration method.
This approach is used by PacketSerial:
https://github.com/bakercp/PacketSerial/blob/master/src/PacketSerial.h#L372

### PR DESCRIPTION
**Pull request by hitech95**
**Summary**

This PR fixes/implements the following **bugs/features**

* [x] #1833

This allow to have TwoWire callbacks methods inside classes. You can use std::bind to wrap the callback functions.

This is an example of a Class that completely handle the I2C comunication without having the user to manually implement the callbacks:

```cpp
/*
 * Lib Functions
 */

I2Client::I2Client(TwoWire *bus)
{
    this->_bus = bus;
}

bool I2Client::begin(uint8_t baseAddress)
{
    _bus->begin(baseAddress);
    _bus->onRequest(std::bind(&I2Client::onHandleRequest, this));

    return true;
}

void I2Client::onHandleRequest()
{
    _bus->write("hello\n");
}

/*
 * Library Usage (main.cpp)
 */

#include <Arduino.h>
#include <Wire.h>

TwoWire bus(PB9, PB8);
I2Client client(&bus);

 void setup()
{
    client.begin(0x4E); // join i2c bus on address 0x4E
}

void loop()
{
    // put your main code here, to run repeatedly:
}
```

**Validation**

* Ensure CI build is passed.
* Demonstrate the code is solid. [e.g. Provide a sketch]

**Code formatting**

* Ensure AStyle check is passed thanks CI

**Closing issues**

Closes #1833

### CODE REVIEW

**Comment by hitech95** [comment]
@fpistm I was thinking the same, I've used the `attachInterrupt` as a reference.
If you think that the failover to void pointers is not necessary I can drop them.

Today I'll do more tests.

**Comment by fpistm** [comment]
> @fpistm I was thinking the same, I've used the `attachInterrupt` as a reference. If you think that the failover to void pointers is not necessary I can drop them.
> 
> Today I'll do more tests.

Yes it is probably the case but requires to be be tested 😉

**Comment by hitech95** [comment]
I've tested with a STM32G030C8T and a MNUCLEO F401 and both works.
(One as a slave and the other as a master and the other way round)

**Comment by fpistm** [comment]
> I've tested with a STM32G030C8T and a NUCLEO F401 and both works. (One as a slave and the other as a master and the other way round)

So you have tested with the c declaration removed ? if it works could you update the PR.

**Comment by hitech95** [comment]
Not yet, I'm gonna do it tomorrow.
I've been quite busy with work.

**Comment by fpistm** [comment]
Hi @hitech95 
any update on this?

**Comment by hitech95** [comment]
Hi
sorry I had lot of issues at work.
I'm gonna do some tests this weekend!

**Comment by fpistm** [comment]
No worry. I understand perfectly  😉

**Comment by hitech95** [comment]
I've tested with the `slave_receive` and `slave_sender` examples from the basic arduino enviroment.
They works also by removing the C failbacks.

So I'm pushing a simplified patch for that.

Tested on Nucleo STM32 F401RE

**Review by fpistm — APPROVED** [review]
LGTM.
Tested on several series.

Thank you @hitech95

**Pull request merged**
