### PR TITLE
Add CMSIS DSP support as built-in library

### LINKED ISSUE #682: DSP functions
Hello, how can i use the CMSIS-DSP functions?
I'm trying to perform an FFT over some samples but i'm not able to import arm_math.h from DSP lib. It does not find any math_arm.h lib from filesystem. I'm pretty sure that the header file is there (view img
Screenshot 2019-10-04 11 59 00
)
i'm using a nucleoF401RE board, and i've installed the stm32core via Arduino IDE board manager

### PR DESCRIPTION
**Pull request by fpistm**
To use it, add:
` #include <CMSIS_DSP.h>`    

`arm_math.h` is then automatically include.

Fixes #682

### CODE REVIEW

**Comment by superpanza** [comment]
Hi @fpistm,
i've just tested your fix but something does not work. CMSIS_DSP.h is not found.
Tell me if i can help you some way

**Comment by fpistm** [comment]
How did you test this PR?
With the git repository and fetch the PR?

**Comment by superpanza** [comment]
> How did you test this PR?
> With the git repository and fetch the PR?

yes i'm testing this PR. Download it and put in place

**Comment by fpistm** [comment]
On top of the repo or of the 1.7.0?
Could you describe exactly how you setup with this PR?

**Comment by superpanza** [comment]
> On top of the repo or of the 1.7.0?
> Could you describe exactly how you setup with this PR?

I had installed stm32duino via arduino  IDE. 
The board manager url used is: https://github.com/stm32duino/BoardManagerFiles/raw/master/STM32/package_stm_index.json
Then from board manager interface i had installed the stm32 cores v.1.7.0.
Now i've downloaded the PR, deleted all the contents of packages/STM32/hardware/stm32/1.7.0/ and paste the new version. 
Screenshot 2019-10-08 14 11 59

**Comment by fpistm** [comment]
Well in that case I don't  know why it does not work.
Could you provide the full log with all verbose and warnings, please.

**Comment by superpanza** [comment]
> Well in that case I don't know why it does not work.
> Could you provide the full log with all verbose and warnings, please.

Ouch my bad!! :-( wrong board selected. Code compiled succesfully! i'm gonna test the FFT in minutes

**Comment by fpistm** [comment]
> Ouch my bad!! :-( wrong board selected. Code compiled succesfully! i'm gonna test the FFT in minutes

So is it ok now?
I wonder if I should add the `math_helper` provided by arm in the DSP library examples.
I think no as it has to be included manually if needed like in the example.

**Comment by yglim** [comment]
Hi. all

Check  compiler.arm.cmsis.c.flags into the platform.txt
the origin is below. 
compiler.arm.cmsis.c.flags="-I{runtime.tools.CMSIS-5.5.1.path}/CMSIS/Core/Include/" "-I{build.system.path}/Drivers/CMSIS/Device/ST/{build.series}/Include/" "-I{build.system.path}/Drivers/CMSIS/Device/ST/{build.series}/Source/Templates/gcc/" "

so I add DSP related location.

compiler.arm.cmsis.c.flags="-I{runtime.tools.CMSIS-5.5.1.path}/CMSIS/Core/Include/" "-I{build.system.path}/Drivers/CMSIS/Device/ST/{build.series}/Include/" "-I{build.system.path}/Drivers/CMSIS/Device/ST/{build.series}/Source/Templates/gcc/" 
**"-I{runtime.tools.CMSIS-5.5.1.path}/CMSIS/DSP/Include"**

stm32duino 1.7.0 noew I'm using.

Happy coding

**Comment by fpistm** [comment]
@yglim 
This will be released with the 1.8.0

**Pull request merged**
