### PR TITLE
SeedStudio LoRa E5 or stm32WLE5JC

### PR DESCRIPTION
**Pull request by sabas1080**
Hi @fpistm 

I'm porting the [LoRa-E5](https://www.seeedstudio.com/LoRa-E5-Wireless-Module-p-4745.html) with STM32WLE5JC

not ready to merge yet, but I would like to receive your feedback

Thanks

### CODE REVIEW

**Comment by fpistm** [comment]
Hi @sabas1080 
First happy new year.
I could not give you any feedback on this as for the moment the STM32WL serie is not supported by this core (HAL/LL drivers, CMSIS device,.... are not added).

**Comment by fpistm** [comment]
@sabas1080
any update on this ?

**Comment by sabas1080** [comment]
Hi @fpistm 

Sorry for the delay. I have started only the variant and I have created the HALs from STMCube. WL and LoraLibrary I have not worked it

**Comment by Sistrum** [comment]
Hello!

I'm very interested in a way to use the STM32WLE5JBI6 with Arduino as well.

@fpistm Did you plan to adapt the Arduino_Core_STM32 to the new boards?

**Comment by fpistm** [comment]
@Sistrum 
this new serie will probably be added.

**Comment by andriyadi** [comment]
Looking forward to the support on this variant.

**Comment by fpistm** [comment]
Hi @sabas1080 
The variant folder organization has changed since the 2.0.0 release and so a new PR could be raised when at least the WL basic support will be added. I close this PR as it will not be merged.
Thanks for your contribution.

**Pull request closed without merging**
