### PR TITLE
Add new board variand F407VE based 3D printer controller

### PR DESCRIPTION
**Pull request by ghent360**
Good sir,

I have this 3D printer controller project (https://github.com/ghent360/PrntrBoard). Initially I used NUCLEO-64 board (F446) to host the MCU. However recently I build a replacement for the NUCLEO-64 "brain" - similar form factor, but using F407VE chip which has a bit more GPIO pins.

This PR add the board variant files. It creatively copies from the DISCO_F407VG as well as the ARMED_V1 variant.

The board schematics is in KiCAD format - open the Nucleo-64-407.pro project, then the Nucleo-64-407.sch schematics file.

~V

### CODE REVIEW

**Comment by fpistm** [comment]
Hi @ghent360 
I will review it next year ;)
Merry Christmas

**Comment by ghent360** [comment]
I tested the ADC, Serial, SPI and GPIO. Marlin seems to be booting fine.

**Comment by ghent360** [comment]
Closed by mistake, sorry. I have to ease on the eggnog.

**Comment by ghent360** [comment]
Thank you @fpistm 
Merry Christmas to you as well.

**Pull request closed without merging**
