### PR TITLE
Added Olimexino-STM32F3 variant

### PR DESCRIPTION
**Pull request by Stanimir-Petev**
**Summary**

This PR adds support for the Olimex board Olimexino-STM32F3 including: GPIO, Analog input, Serial UART, I2C, SPI, CAN.
In order to make variant for this board (Olimexino-STM32F3) the variant for Generic STM32F3 (PILL_F303XX) series was taken as a base and then modified to match the hardware configuration.

**Link to the board on our website**
https://www.olimex.com/Products/Duino/STM32/OLIMEXINO-STM32F3/

**PDF of the board schematic**
[OLIMEXINO-STM32F3_RevB.pdf](https://github.com/stm32duino/Arduino_Core_STM32/files/4895103/OLIMEXINO-STM32F3_RevB.pdf)

**Peripheral examples**
[Olimexino-STM32F3_examples.zip](https://github.com/stm32duino/Arduino_Core_STM32/files/4894968/Olimexino-STM32F3_examples.zip)

Notes:
1) I2C example is using MOD-BME280 (https://www.olimex.com/Products/Modules/Sensors/MOD-BME280)
2) SPI example is using MOD-LCD3310 (https://www.olimex.com/Products/Modules/LCD/MOD-LCD3310/)
3) MOD-LCD3310 + SD card example doesn't work with the default SPI library due to the single SPI object.

### CODE REVIEW

**Comment by fpistm** [comment]
Hi @Stanimir-Petev 
thanks for this PR.
I know the OLIMEXINO STM32F103:
https://www.olimex.com/Products/Duino/STM32/OLIMEXINO-STM32/open-source-hardware

but I could not find any link on an OLIMEXINO F303, could you share some inputs?

**Comment by Stanimir-Petev** [comment]
> Hi @Stanimir-Petev
> thanks for this PR.
> I know the OLIMEXINO STM32F103:
> https://www.olimex.com/Products/Duino/STM32/OLIMEXINO-STM32/open-source-hardware
> 
> but I could not find any link on an OLIMEXINO F303, could you share some inputs?

Hi @fpistm !
Thanks for the fast reply and the tag you made!
I am an Olimex employee. This board is just a prototype yet to be released. Hope we get it out soon.

For now I am making only a draft of the PR to see if it will meet the checks requirements and soon I will edit the description. If needed I can post some pictures and/or pdf of the schematic. Also I can provide few examples of the different peripherals, although the one for SD card require a patch in the SPI library (which is probably a subject for another PR). All others works on the prototype I have.

**Comment by fpistm** [comment]
Will be added later when #1091 will be done

**Comment by fpistm** [comment]
Hi @Stanimir-Petev 
I've included your PR in #1091, it has been reformatted to the new variant definition way.
So I close this one as it is superseded by #1091.
Thanks again for your contribution.

>     3\. MOD-LCD3310 + SD card example doesn't work with the default SPI library due to the single SPI object.

About this, a first issue is that `SDCARD_SS_PIN` should be defined to `PD2` as it is the real CS for the SD card slot (Software chip select). `PB12` is the hardware CS which is not the same. And yes `SPI_2` is not instantiate by default. This would be achieve thanks #705  and the support of `SPI_INTERFACES_COUNT`.
I've successfully tested the embedded SD card slot using the default SD Arduino library using card info example, to test it you can modify the sketch like this:

```patch
- const int chipSelect = 4;
+ const int chipSelect = SDCARD_SS_PIN;
```

```patch
-
+  SPI.setMISO(PB14);
+  SPI.setMOSI(PB15);
+  SPI.setSCLK(PB13);
  Serial.print("\nInitializing SD card...");
```

**Pull request closed without merging**
