### PR TITLE
Add STM32F446VE controller board

### PR DESCRIPTION
**Pull request by fpistm**
Replace #522 
From @petervanaken 
**Summary**

This PR implements the following : Introduction of a new board called VAkE v1.0. This board is based upon the STM32F446VE. It can be used as 3D printer / CNC controller board with versatile stepper configuration. 
All comments are welcome.
Please find more info about the VAkE PCB : https://www.facebook.com/pages/category/Product-Service/VAkE-Board-2290066274575218/ 
Cheers,
Peter

### CODE REVIEW

**Comment by fpistm** [comment]
@petervanaken
do not hesitate to comment and give feedback on this PR.
Mainly about boards.txt and name used

**Comment by petervanaken** [comment]
I've tested the PR on target and everything looks fine to me.
What else needs to be done to merge with the master ?
Cheers,
Peter

**Comment by fpistm** [comment]
Hi @petervanaken 
The main things is the naming in the menu. If you are agreed then I could merge it.

**Comment by petervanaken** [comment]
Yes, the naming looks fine. 
Cheers, 
Peter

**Comment by fpistm** [comment]
@petervanaken 
FYI, I've referenced the board in the README.md

**Comment by petervanaken** [comment]
Great :-D , thanks !

**Pull request merged**
