### PR TITLE
[New variant] Add Generic STM32G0 boards menu, Aurora One Variant

### PR DESCRIPTION
**Pull request by jhleekr**
**Summary
Added Generic STM32G0 boards menu in readme, boards.txt,
Added Aurora One Variant**

Tested blink example and there was no problem.

Here is some information about this board:
summary: https://www.bfykorea.com/aurora-one/
schematic: https://www.bfykorea.com/files/Schematic_BFY-Aurora-One_Final_rev1.2.pdf

### CODE REVIEW

**Comment by fpistm** [comment]
Will be added later when #1091 will be done

**Comment by fpistm** [comment]
Hi @jhleekr 
I've included you PR in #1091, it has been reformatted to the new variant definition way. I've made some fix.
So I close this one as it is superseded by #1091.
Thanks again for your contribution and also nice board 😉

**Comment by jhleekr** [comment]
OK. Thank you :)

**Comment by jhleekr** [comment]
Hi @fpistm 
There's a new variant to add, but it doesn't seem like the reformatting to the new variant definition way is complete.
Further information below. Could you check if it could be added?

Aurora Micro
summary: https://www.bfy.kr/aurora-micro/
schematic: https://www.bfy.kr/wp-content/uploads/2020/08/Schematic_BFY-Aurora-Micro_Final.pdf
definition files: https://github.com/jhleekr/Arduino_Core_STM32/tree/master/variants/AURORA_MICRO_G031G8

**Comment by fpistm** [comment]
The new formatting is on going and almost ready but it take time to reformat all existing variants.
I will not add the new aurora micro mentioned. I've reformatted your PR for the Aurora one. The micro one will have to be added as a new PR.

**Comment by jhleekr** [comment]
Then, can I open a new PR now? Or is it necessary to open the PR after writing in a new format after the new formatting is completed?

**Comment by fpistm** [comment]
The best would be to wait.

**Comment by jhleekr** [comment]
Okay. Thanks.

**Pull request closed without merging**
