### PR TITLE
Core Board F401RC

### LINKED ISSUE #594: [New Variant]STM32F401
Helllo, Thanks for the huge quantity of work!

I would like to know if you plan to include in the release 1.7.0 these generic variants for F401

STM32F401CC in UFQFPN48 and LQFP64 packages

STM32F401RCT6  in  LQFP64 package

Generally speaking how do you handle the different packages versions?

### PR DESCRIPTION
**Pull request by fpistm**
Fixes #594

Based on @mrguen first try for this board:
 https://fr.aliexpress.com/item/32894670982.html?spm=a2g0s.9042311.0.0.27426c37RrpWiJ

Shematics: [STM32F401RCT6_CORE_BOARD_原理图.pdf](https://github.com/stm32duino/Arduino_Core_STM32/files/3519013/STM32F401RCT6_CORE_BOARD_.pdf)
Pinouts [STM32F401RCT6_CORE_BOARD尺寸图.pdf](https://github.com/stm32duino/Arduino_Core_STM32/files/3519014/STM32F401RCT6_CORE_BOARD.pdf)

### CODE REVIEW

**Comment by mrguen** [comment]
Sorry I tested only if analogRead() and digitalRead() on all ad hoc pins are ok.  I would try to test the rest later if you mind.

**Comment by mrguen** [comment]
@fpistm 
Could you explain me more about the DFU and Serial download mode. Here is what I see

1) Download using DFU on a board just attached to the USB port and seen as "STM32 bootloader" by windows. Download method STM32CubeProgrammer (DFU), Boot0 = 1

Works. Then the device COM port is enumerated. Then DFU download is not possible anymore and results in 

`"Error: Target device not found - Establishing connection with the device failed"`

2) Ok, so I try to download using STM32CubeProgrammer (Serial) / seleting the COM port . The device is seen as "STM Serial" by windows. Tested Either in BOOT0 = 0 or BOOT0=1 results in:

```
"Serial Port COM29 is successfully opened.
Port configuration: parity = even, baudrate = 115200, data-bit = 8,
                     stop-bit = 1.0, flow-control = off

Timeout error occured while waiting for acknowledgement.

Timeout error occured while waiting for acknowledgement.
Error: Activating device: KO. Please, verify the boot mode configuration and check the serial port configuration. Reset your device then try again... "
```
3) So at the moment the only solution is to set BOOT0 = 1 and  reset the device everytime so it is seen as a DFU device and not enumerated as a Serial device.

**Comment by fpistm** [comment]
@mrguen 
all is explained in this document:
https://www.st.com/content/ccc/resource/technical/document/application_note/b9/9b/16/3a/12/1e/40/0c/CD00167594.pdf/files/CD00167594.pdf/jcr:content/translations/en.CD00167594.pdf

image

So timeout you get in for serial upload is due to no ack from the board about the 0x7F. You have to reset the board then it will acknowledge properly.
For DFU yes you have to reset it to switch to DFU mode.

I've planned to add an automatic reset in bootloader mode thanks a special sequences on the Serial line as it is done for HID BL or Maple DFU BL.

**Comment by mrguen** [comment]
Either I manual reset or not it will not upload using STM32CubeProgrammer (Serial).

There is no delay before printing the error... there is no time for scanning a device (and pressing the switch). The device is enumerated in Windows "STM Serial (COM29)"

Now it raises:
`"Error: Cannot open port COM29, it may be used by another application or port name is invalid."`

**Comment by fpistm** [comment]
This is not related to the core.
It is a STM32CubeProgrammer/STM32 Bootloader usage. 
I guess you should ask on [ST community](https://community.st.com/).

**Comment by mrguen** [comment]
Ok, I will continue testing the device uploading with reset / DFU because it is way over my head and I would like to finish this.

**Comment by mrguen** [comment]
So far I could not validate these tests:

Serial 6 on PC7/PC6: not working (Serial 1 and 2 ok)
I2C1 on PB3/PB10: not working (I2C2 ok): maybe related to issue #463 ?

**Comment by fpistm** [comment]
PB3/PB10 is only I2C2.
How do you test USART6? Sketch?

**Comment by mrguen** [comment]
Sorry my comment was false. I tested I2C1 on PB7/PB6. I just modified my comment.

I tested Serial 6 with SerialCallResponse.ino modified with instantiating
Serial6 HardwareSerial SerialN6(PC7, PC6);

**Comment by fpistm** [comment]
Well I guess you do not pay attention to pin mapping, SerialCallResponse set the pin number 2 in `INPUTpinMode(2, INPUT);   // digital sensor is on digital pin 2`
and digital pin number 2 is... `PC6` so I guess this could cause some trouble to rest USART6 TX pin to INPUT...

And how do you test I2C1 on PB7/PB6

**Comment by mrguen** [comment]
Ok, thanks. Serial 6 is working.

I2C works when instantiating TwoWire Wire1(PB7, PB6);  but not with the default Wire instance.

**Comment by fpistm** [comment]
Which is normal as the default Wire instance is on PB8 (SDA) / PB9 (SCL)... 
To change the default pins used by the default instance see:
https://github.com/stm32duino/wiki/wiki/API#i2c

**Comment by mrguen** [comment]
Ok, so these tests passed:
* Blink
* Serial through USB
* Serial1 PA9/PA10
* Serial 2 PA2/PA3
* Serial 6 PC7/PC6
* I2C1 PB9/PB8
* I2C2 PB3/PB10
* AnalogReadSerial - all adc pins
* DigitalReadSerial - all digital pins
* Watchdog timer
* SPI1 with a 0.96" TFT   Display

I could not write to EEPROM (eeprom_write.ino) the value '100' and then read it (eeprom_read.ino). It constantly reads 255.

**Comment by fpistm** [comment]
Thanks for the tests.
Try eeprom_put/get instead.

**Comment by mrguen** [comment]
Yes, passed:
* eeprom_put 
* eeprom_get 

I suppose eeprom_write and eeprom_read have a datatype problem but won't investigate it.

**Comment by mrguen** [comment]
@fpistm Thanks for your constant support.

**Pull request merged**
