### PR TITLE
Allow setting PWM freq

### PR DESCRIPTION
**Pull request by edogaldo**
introduced new function PWMWrite() which allows generating PWM signals with specified freq

### CODE REVIEW

**Comment by edogaldo** [comment]
**Note: being the frequency shared among all channels of a specified timers, setting the freq for one channel (pin) will impact all others.**

**Comment by edogaldo** [comment]
No, maybe I'm not..
@fpistm: could you please confirm that PWM_FREQUENCY represents the frequency of the PWM signal?

Thanks in advance, E.

**Comment by fpistm** [comment]
Yes but depending of its value this will not be the case due to the computation done. (If I well remember).
I would not like introduce this PR while the HardwareTimer is not released.

**Comment by fpistm** [comment]
@edolgado, I've do a new PR to provide a way to update Freq.
As I do not want introduce new API naming ( `PWMxxxx()` ) while not review Timer feature.
This only introduce a way to change de he default freq using a Arduinoish API liked `analogWriteResolution`

**Pull request closed without merging**
