### PR TITLE
Add generic F410Cx pinout

### PR DESCRIPTION
**Pull request by MCUdude**
This pinout shares the same layout as the Generic F401Cx and F411Cx.

I followed the instructions you gave in the other PR, but the made Github delete the entire PR. Well, here it is again!

### CODE REVIEW

**Comment by fpistm** [comment]
Thanks @MCUdude 
Some advice for the next PR:
- Please add a blank line between commit title and commit description. You can refers to the Contributing.md about good practice for commit message.
- Reference the new board(s) in the README.md as it is done for other new one.
- You can remove all "ST-link" related comments for the UART definition.

Thanks 😉

**Comment by MCUdude** [comment]
> Please add a blank line between commit title and commit description. You can refers to the Contributing.md about good practice for commit message.

I've always used just a blank space. I'll use a line instead!

The only low-pin-count STM32F4's that are missing are currently F405/F415, F412 and F413/423.

Is the name *Generic_F4x5Rx* an OK name for generic F405/F415Rx's?

**Comment by fpistm** [comment]
> Is the name _Generic_F4x5Rx_ an OK name for generic F405/F415Rx's?

If F405 and 415 are closed (same Peripherals Pins) well OK

**Comment by MCUdude** [comment]
> If F405 and 415 are closed (same Peripherals Pins) well OK

Yes, I've compared the source files I've gotten from the Arduino Tools repo. They are identical except that F415 has some crypto hardware as well. Apart from this, they are completely identical. This is also the case for F413/423 🙂

**Pull request merged**
