### PR TITLE
feat: Add variant NUCLEO-C071RB

### LINKED ISSUE #2537: [New Variant] NUCLEO-C071RB
**Board description (please complete the following information):**
 - Name: NUCLEO-C071RB
 - Link to all relevant information: https://www.st.com/en/evaluation-tools/nucleo-c071rb.html

### PR DESCRIPTION
**Pull request by thernstig**
Fixes #2537

### CODE REVIEW

**Comment by thernstig** [comment]
@fpistm I have _NO_ idea if this is correct. I could not find any guideline on how to do for Nucleos. I took a look at https://github.com/stm32duino/Arduino_Core_STM32/pull/1745/files when doign this.

It seems I should have done changes in the variant_NUCLEO_C071RB.cpp and variant_NUCLEO_C071RB.h files in some way, that I probably got wrong.

I am completely ok with you updating anything in this commit manually.

I have no idea how to test it.

**Comment by fpistm** [comment]
Hi @thernstig 
Could you rebase this PR on the main.
It requires to get the generic to be able to build (ldscript.ld).

**Comment by thernstig** [comment]
@fpistm Rebase done.

Are any updates needed in the .cpp and .h file? I have no idea what is needed there.

**Comment by fpistm** [comment]
@thernstig 
I will review this afternoon. I will made the change.

**Comment by fpistm** [comment]
@thernstig 
I've updated your branch.
- fix astyle issue
- order the pins to match board pinout (mainly Arduino Uno connector) and set the analog pins order.
- Define the USER_BTN, LED,...
- Add the USB support since STM32C071xx support USB. (not tested, only build enable)

**Review by fpistm — APPROVED** [review]
LGTM

**Comment by thernstig** [comment]
@fpistm thank you! If you think this looks ok I am ok to merge as well

**Comment by fpistm** [comment]
> Are you intending to release 2.9.0 soon

Yes, in the coming days, anyway think that I've not tested this PR as I do not have the board. Anyway, I'm confident that it should work. Only a doubt about USB as it is the first time deployed on STM32C0xx series.

**Pull request merged**
